--
-- Daten für Tabelle `help_messages`
--

INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(346, 0, 10100, -1, 'de', 'Typ', 'Der Typ bestimmt die Art und Funktionsweise des Feldes. Es stehen zur Auswahl: Textfeld, Nummernfeld, Datum, Auswahlliste und Tabelle.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(347, 0, 10101, -1, 'de', 'ID', 'Die ID eines Feldes muss eindeutig sein, da ansonsonsten die Daten nicht korrekt zu den Feldern zugeordnet werden können. Beim Hinzufügen eines Feldes wird auf eine eindeutige ID hin geprüft und ggf. eine Fehlermeldung ausgegeben. Eine ID kann aus einer beliebigen Zeichenkette bestehen und sollte einen sinnvollen Namen erhalten. Nachdem die ID einmal vergeben wurde kann diese nicht mehr bearbeitet werden.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(348, 0, 10102, -1, 'de', 'Pflichtfeld', 'Wird diese Auswahl aktiviert, so wird das Feld als ein Pflichtfeld behandelt. Es wird dann fett mit einem "*" dargestellt. Außerdem wird beim Veröffentlichen eines Objektes, daraufhin überprüft, ob dieses Feld leer ist. Nur wenn es Daten enthält, kann das Objekt dann veröffentlicht werden. Die Sichtbarkeit wird automatisch auf "sichtbar" gesetzt, da Pflichtfelder immer angezeigt werden sollen. Wenn die Auswahl deaktiviert ist, so wird dieses Feld als optional angenommen.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(349, 0, 10103, -1, 'de', 'Sichtbarkeit', 'Es gibt verschiedene Optionen, die die Sichtbarkeit eines Feldes beeinflussen. <dl><dt>optional</dt><dd>Initial ist das Feld ausgeblendet und wird erst durch das Ausklappen der dazugehörigen Rubrik sichtbar.</dd><dt>anzeigen</dt><dd>Das Feld wird immer angezeigt, auch wenn die Rubrik eingeklappt ist. Dies ist die Standardeinstellung für Pflichtfelder.</dd><dt>verstecken</dt><dd>Das Feld wird permanent ausgeblendet, wodurch auch keine neuen Daten für dieses Feld aufgenommen werden können.</dd></dl>', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(350, 0, 10104, -1, 'de', 'Beschriftung', 'Hier wird die Beschriftung des Feldes angegeben. Diese kann in verschiedenen Sprachen angegeben werden, wobei die Erste (normalerweise Englisch) angegeben werden muss! Wird der InGrid-Editor in einer Sprache ausgeführt, wo es keine Beschriftung zum Feld gibt, so wird hier die Standardsprache (Englisch) verwendet.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(351, 0, 10105, -1, 'de', 'Hilfetext', 'Hier wird die Hilfetext des Feldes angegeben, welcher durch ein Klick auf die Beschriftung angezeigt wird. Diese kann in verschiedenen Sprachen angegeben werden, wobei die Erste (normalerweise Englisch) angegeben werden muss! Wird der InGrid-Editor in einer Sprache ausgeführt, wo es keinen Hilfetext zum Feld gibt, so wird hier die Standardsprache (Englisch) verwendet.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(352, 0, 10106, -1, 'de', 'Skripte', 'In diesem Bereich ist es möglich, zusätzlich JavaScript Code beim Starten des InGrid-Editors auszuführen. Dieser kann dazu dienen, dass ein Feld bspw. auf spezielle Ereignisse reagiert oder die funktionsweise des Feldes sogar erweitert.<br/>Unter dem IDF-Mapping wird der Code in JavaScript hinterlegt, welcher für die Abbildung des Feldes in das Ingrid-Daten-Format benötigt wird.', '// lässt in einer Textbox (mit ID "userEmail") nur gültige Emailadressen zu<br/>dijit.byId("userEmail").regExpGen = dojox.validate.regexp.emailAddress;<br/><br/>// spezielle Überprüfung eines Textfeldes<br/>dijit.byId("doNotAllowNoInTextfield").validator = function(value) {if (value == "NO") return false; else return true;}<br/><br/>// Überprüfung vor einer Veröffentlichung<br/>dojo.subscribe("/onBeforeObjectPublish", function(/*Array*/notPublishableIDs) { if (dijit.byId("aField").get("value")) == "Kein" notPublishableIDs.push("aField");})');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(353, 0, 10107, -1, 'de', 'Optionen', 'Hier werden die Einträge für die Auswahlliste definiert. Die "id" wird automatisch vergeben und wird benötigt, um eine korrekte Zuordnung zu den verschiedenen Sprachversionen eines Listeneintrags zu gewährleisten. Es ist außerdem möglich, die Reihenfolge der Einträge zu verändern, indem man den "Griff" in der ersten Spalte an die gewünschte Position verschiebt.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(354, 0, 10108, -1, 'de', 'Einheit', 'Die Einheit, die hinter der Zahlentextbox angezeigt werden soll. Ist dieses Feld leer, so wird keine Einheit angezeigt.', 'cm, km, Euro');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(355, 0, 10109, -1, 'de', 'Indexname', 'Gibt an, unter welchem Namen dieses Feld im Index abgelegt werden soll. Bleibt dieses Feld leer, so wird dieses Feld auch nicht im Index gespeichert.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(356, 0, 10110, -1, 'de', 'Breite', 'Gibt die Breite des Feldes in Prozent an. 100% gilt für die gesamte Breite, wohingegen 50% die halbe verfügbare Breite in Anspruch nimmt. Werden zwei aufeinanderfolgende Felder mit einer Breite von jeweils 50% angelegt, so werden diese im InGrid-Editor nebeneinander angezeigt. Durch andere prozentuale Verteilungen, lassen sich so auch andere Anordnungen erzeugen.', 'Breite: 100');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(357, 0, 10111, -1, 'de', 'Anzahl der Zeilen', 'Wird ein Textfeld erstellt, so bietet sich die Möglichkeit, die Anzahl der darzustellenden Zeilen zu definieren.', '3');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(358, 0, 10112, -1, 'de', 'Anzahl der Reihen', 'Bei Tabellen wird hier definiert, wieviele Reihen diese Tabelle mindestens anzeigen soll.', 'Default: 4');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(359, 0, 10113, -1, 'de', 'Spaltendefinition', 'Hier können Spalten hinzugefügt oder aber auch gelöscht werden. Die verschiedenen Spaltentypen sind: Textfeld, Nummernfeld, Datum und Auswahlliste. Bei der Erstellung einer Tabelle muss mindestens eine Spalte angegeben werden!', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(360, 0, 10114, -1, 'de', 'Erlaube freie Einträge', 'Wird diese Option aktiviert, so kann zu dieser Auswahlliste im InGrid-Editor auch ein freier Eintrag verwendet und abgespeichert werden. Andernfalls kann nur ein Eintrag aus der vordefinierten Liste ausgewählt werden. Die Einträge können in verschiedenen Sprachen angegeben werden, so dass bei der Verwendung einer anderen Sprache im InGrid-Editor sich auch der Listeneintrag an die ausgewählte Sprache anpasst.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(361, 0, 10150, -1, 'de', 'Typ', 'Der Typ des Feldes für diese Spalte. Dieser kann ein Textfeld, Nummernfeld, Datum oder eine Auswahlliste sein.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(362, 0, 10151, -1, 'de', 'ID', 'Die ID der Spalte muss eindeutig innerhalb einer Tabelle sein!', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(363, 0, 10152, -1, 'de', 'Beschriftung', 'Hier wird die Beschriftung des Feldes angegeben. Diese kann in verschiedenen Sprachen angegeben werden, wobei die Erste (normalerweise Englisch) angegeben werden muss! Wird der InGrid-Editor in einer Sprache ausgeführt, wo es keine Beschriftung zum Feld gibt, so wird hier die Standardsprache (Englisch) verwendet.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(364, 0, 10153, -1, 'de', 'Optionen', 'Hier werden die Einträge für die Auswahlliste definiert. Die "id" wird automatisch vergeben und wird benötigt, um eine korrekte Zuordnung zu den verschiedenen Sprachversionen eines Listeneintrags zu gewährleisten. Es ist außerdem möglich, die Reihenfolge der Einträge zu verändern, indem man den "Griff" in der ersten Spalte an die gewünschte Position verschiebt.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(365, 0, 10154, -1, 'de', 'Breite', 'Gibt die Breite der Spalte in Pixeln an.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(366, 0, 10155, -1, 'de', 'Indexname', 'Gibt an, unter welchem Namen dieses Feld im Index abgelegt werden soll. Bleibt dieses Feld leer, so wird dieses Feld auch nicht im Index gespeichert.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(367, 0, 10156, -1, 'de', 'Erlaube freie Einträge', 'Wird diese Option aktiviert, so kann zu dieser Auswahlliste im InGrid-Editor auch ein freier Eintrag verwendet und abgespeichert werden. Andernfalls kann nur ein Eintrag aus der vordefinierten Liste ausgewählt werden. Die Einträge können in verschiedenen Sprachen angegeben werden, so dass bei der Verwendung einer anderen Sprache im InGrid-Editor sich auch der Listeneintrag an die ausgewählte Sprache anpasst.', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(368, 0, 3000, 6, 'de', 'Objektname', 'Angabe einer kurzen prägnanten Bezeichnung des beschriebenen Dienstes / der beschriebenen Anwendung / des beschriebenen Informationssystems. Der Objektname kann z.B. identisch mit dem Namen des Dienstes /der Anwendung /des Informationssystems sein, sofern dieser ausreichend kurz und aussagekräftig ist. Soweit ein gängiges Kürzel vorhanden ist, ist dieses Kürzel mit anzugeben. Der Eintrag in dieses Feld ist obligatorisch.', 'Emissions-Fernüberwachung EFÜ');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(369, 0, 6000, -1, 'de', 'INSPIRE-relevanter Datensatz', 'Dieses Feld definiert, wenn aktiviert, dass ein Metadatensatz für das INSPIRE-Monitoring vorgesehen ist.', '');

UPDATE help_messages SET help_text = 'Angabe einer kurzen prägnanten Bezeichnung des beschriebenen Geodatendienstes. Der Objektname kann z.B. identisch mit dem Namen des Geodatendienstes sein, sofern dieser ausreichend kurz und aussagekräftig ist. Soweit ein gängiges Kürzel vorhanden ist, ist dieses Kürzel mit anzugeben. Der Eintrag in dieses Feld ist obligatorisch.' WHERE help_messages.id = 37;
UPDATE help_messages SET help_text = 'OGC Web Service: Angaben zur Implementierungsgeschichte des Dienstes. Bei anderen Systemen Angabe zur Entwicklungsgeschichte. Hier können Vorläufer und Folgedienste genannt werden. Ebenso sind Angaben zu initiierenden Forschungsvorhaben oder -programmen von Interesse.' WHERE help_messages.id = 50;
UPDATE help_messages SET help_text = 'OGC Web Services: Beschreibung der Basisdaten. Allgemein: Zusätzliche Anmerkungen zu dem beschriebenen Geodatendienst. Hier können weitergehende Angaben z. B. technischer Art gemacht werden, die zum Verständnis des Geodatendienstes notwendig sind.' WHERE help_messages.id = 51;
UPDATE help_messages SET name = 'Datendefizit' WHERE help_messages.id = 76;
UPDATE help_messages SET help_text = 'Eingabe einer Prozentangabe zum Stand des Datendefizites des Datenobjektes. Diese kann sich auf die Anzahl der Kartenblätter aber auch auf den Erfassungsgrad einer Gesamtkarte beziehen.' WHERE help_messages.id = 76;
UPDATE help_messages SET help_text = 'Informationen über die räumliche Zuordnung des in dem Objekt beschriebenen Datenbestand. Es können frei wählbare Raumbezugs-Koordinaten hinzugefügt werden. Der Wertebereich im WGS ist folgendermaßen definiert: <ul><li>Breite (Latitude): -90 bis 90</li><li>Länge (Longitude): -180 bis 180</li></ul>' WHERE help_messages.id = 311;
UPDATE help_messages SET name = 'Zeitbezug der Resource' WHERE help_messages.id = 128;
UPDATE help_messages SET help_text = 'Angabe, wann die Resource erstellt, revidiert und/oder publiziert wurde.' WHERE help_messages.id = 128;
