FROM php:8.3-apache@sha256:41ce934bddbd1b79927187723bbfeab8ec730d1604bbbf5b00ce98cd3c4ac5af

ENV GRAV_VERSION=2.0.22
ENV YQ_VERSION=v4.45.1
ENV TZ='Europe/Berlin'

# Update system
RUN apt-get update

# Install dependencies
RUN apt-get install -y libzip-dev libpng-dev libjpeg-dev unzip vim libxslt1-dev libxml2 cron wget

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Configure and install PHP extensions
RUN docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install zip gd xsl xml dom intl

WORKDIR /var/www
RUN curl -o grav-admin.zip -SL https://github.com/getgrav/grav/releases/download/${GRAV_VERSION}/grav-admin-v${GRAV_VERSION}.zip && \
    unzip grav-admin.zip && \
    cp -rT /var/www/grav-admin /var/www/html && \
    rm grav-admin.zip

RUN chown -R --from=root:root www-data:www-data /var/www/html
RUN pecl install xdebug

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install yq
RUN wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 \
 && chmod +x /usr/local/bin/yq

COPY entrypoint_dev.sh /entrypoint.sh
COPY develop/99-xdebug.ini /usr/local/etc/php/conf.d/99-xdebug.ini

# Enable mod_rewrite for Apache
RUN a2enmod rewrite

USER www-data
RUN cd html &&  \
    bin/gpm install devtools

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
