/*
 * **************************************************-
 * Ingrid Portal Apps
 * ==================================================
 * Copyright (C) 2014 wemove digital solutions GmbH
 * ==================================================
 * Licensed under the EUPL, Version 1.1 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 * 
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl5
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * **************************************************#
 */
({"lightsteelblue":"浅钢�?色","orangered":"橙红色","midnightblue":"深�?色","cadetblue":"�?��?色","seashell":"海�?色","slategrey":"�?�石色","coral":"�?�瑚色","darkturquoise":"深粉�?","antiquewhite":"�?�董白","mediumspringgreen":"间春绿色","salmon":"橙红","darkgrey":"深�?�色","ivory":"象牙色","greenyellow":"绿黄色","mistyrose":"浅玫瑰色","lightsalmon":"淡橙色","silver":"银白色","dimgrey":"暗�?�色","orange":"橙色","white":"白色","navajowhite":"纳瓦白","royalblue":"�?�?","deeppink":"深粉红色","lime":"淡黄绿色","oldlace":"�?白色","chartreuse":"黄绿色","darkcyan":"深�?�绿","yellow":"黄色","linen":"亚麻色","olive":"橄榄绿","gold":"金黄色","lawngreen":"�?�绿色","lightyellow":"浅黄色","tan":"棕�?色","darkviolet":"深紫色","lightslategrey":"浅�?��?�","grey":"�?�色","darkkhaki":"深�?�其色","green":"绿色","deepskyblue":"深天�?色","aqua":"浅绿色","sienna":"赭色","mintcream":"薄�?�色","rosybrown":"�?玫瑰红","mediumslateblue":"间暗�?色","magenta":"洋红色","lightseagreen":"浅海藻绿","cyan":"�?��?色","olivedrab":"�?�绿色","darkgoldenrod":"深金黄","slateblue":"石�?色","mediumaquamarine":"间绿色","lavender":"淡紫色","mediumseagreen":"间海�?色","maroon":"栗色","darkslategray":"深�?��?�","mediumturquoise":"间绿�?石色","ghostwhite":"�?白","darkblue":"深�?","mediumvioletred":"间紫罗兰色","brown":"棕色","lightgray":"浅�?�色","sandybrown":"沙�?色","pink":"粉红色","firebrick":"砖红","indigo":"�?��?�","snow":"雪白色","darkorchid":"深紫色","turquoise":"绿�?石色","chocolate":"巧克力色","springgreen":"春绿色","moccasin":"鹿皮色","navy":"�?�?�色","lemonchiffon":"柠檬绸色","teal":"水鸭色","floralwhite":"花白色","cornflowerblue":"浅�?色","paleturquoise":"�?绿色","purple":"紫色","gainsboro":"淡�?�色","plum":"�?��?�色","red":"红色","blue":"�?色","forestgreen":"森林绿","darkgreen":"深绿色","honeydew":"蜜�?色","darkseagreen":"深海藻绿","lightcoral":"浅�?�瑚色","palevioletred":"�?紫罗兰色","mediumpurple":"间紫色","saddlebrown":"�?�?色","darkmagenta":"深洋红色","thistle":"蓟色","whitesmoke":"烟白色","wheat":"浅黄色","violet":"紫色","lightskyblue":"浅天�?色","goldenrod":"金麒麟色","mediumblue":"间�?色","skyblue":"天�?色","crimson":"绯红色","darksalmon":"深橙红","darkred":"深红色","darkslategrey":"深�?��?�","peru":"秘�?色","lightgrey":"浅�?�色","lightgoldenrodyellow":"浅金黄色","blanchedalmond":"白�??色","aliceblue":"爱丽�?�?","bisque":"桔黄色","slategray":"�?�石色","palegoldenrod":"淡金黄色","darkorange":"深橙色","aquamarine":"碧绿色","lightgreen":"浅绿色","burlywood":"实木色","dodgerblue":"闪�?色","darkgray":"深�?�色","lightcyan":"浅�?�色","powderblue":"�?�?","blueviolet":"�?紫色","orchid":"紫色","dimgray":"暗�?�色","beige":"米色","fuchsia":"紫红色","lavenderblush":"淡紫红","hotpink":"深粉红","steelblue":"钢�?色","tomato":"西红柿色","lightpink":"浅粉红色","limegreen":"橙绿色","indianred":"�?�度红","papayawhip":"木瓜色","lightslategray":"浅�?��?�","gray":"�?�色","mediumorchid":"间紫色","cornsilk":"米绸色","black":"黑色","seagreen":"海绿色","darkslateblue":"深�?��?","khaki":"�?�其色","lightblue":"淡�?色","palegreen":"淡绿色","azure":"天�?色","peachpuff":"桃色","darkolivegreen":"深橄榄绿","yellowgreen":"黄绿色"})