rmdir /Q /S dijit\tests
rmdir /Q /S dijit\themes\themeTesterImages
rmdir /Q /S dojo\tests
rmdir /Q /S dojox\analytics\tests
rmdir /Q /S dojox\app\tests
rmdir /Q /S dojox\atom\tests
rmdir /Q /S dojox\av\tests
rmdir /Q /S dojox\calc\tests
rmdir /Q /S dojox\calendar\tests
rmdir /Q /S dojox\charting\tests
rmdir /Q /S dojox\collections\tests
rmdir /Q /S dojox\color\tests
rmdir /Q /S dojox\data\tests
rmdir /Q /S dojox\date\tests
rmdir /Q /S dojox\dgauges\tests
rmdir /Q /S dojox\dnd\tests
rmdir /Q /S dojox\drawing\tests
rmdir /Q /S dojox\dtl\tests
rmdir /Q /S dojox\editor\tests
rmdir /Q /S dojox\embed\tests
rmdir /Q /S dojox\encoding\tests
rmdir /Q /S dojox\flash\tests
rmdir /Q /S dojox\form\tests
rmdir /Q /S dojox\fx\tests
rmdir /Q /S dojox\gantt\tests
rmdir /Q /S dojox\gauges\tests
rmdir /Q /S dojox\geo\charting\tests
rmdir /Q /S dojox\geo\openlayers\tests
rmdir /Q /S dojox\gesture\tests
rmdir /Q /S dojox\gfx3d\tests
rmdir /Q /S dojox\gfx\tests
rmdir /Q /S dojox\grid\tests
rmdir /Q /S dojox\highlight\tests
rmdir /Q /S dojox\html\tests
rmdir /Q /S dojox\image\tests
rmdir /Q /S dojox\io\tests
rmdir /Q /S dojox\io\proxy\tests
rmdir /Q /S dojox\json\tests
rmdir /Q /S dojox\jsonPath\tests
rmdir /Q /S dojox\lang\tests
rmdir /Q /S dojox\layout\tests
rmdir /Q /S dojox\math\tests
rmdir /Q /S dojox\mdnd\tests
rmdir /Q /S dojox\mobile\tests
rmdir /Q /S dojox\mvc\tests
rmdir /Q /S dojox\NodeList\tests
rmdir /Q /S dojox\rails\tests
rmdir /Q /S dojox\robot\tests
rmdir /Q /S dojox\rpc\tests
rmdir /Q /S dojox\secure\tests
rmdir /Q /S dojox\sketch\tests
rmdir /Q /S dojox\store\tests
rmdir /Q /S dojox\storage\tests
rmdir /Q /S dojox\string\tests
rmdir /Q /S dojox\testing
rmdir /Q /S dojox\timing\tests
rmdir /Q /S dojox\treemap\tests
rmdir /Q /S dojox\uuid\tests
rmdir /Q /S dojox\validate\tests
rmdir /Q /S dojox\widget\tests
rmdir /Q /S dojox\widget\DocTester
rmdir /Q /S dojox\wire\tests
rmdir /Q /S dojox\xml\tests
rmdir /Q /S dojox\xmpp\tests
rmdir /Q /S util\buildscripts\tests
rmdir /Q /S util\docscripts\tests
rmdir /Q /S util\doh\tests
rmdir /Q /S util\shrinksafe\tests

pause