
-- Execute on MYSQL portal database after migration to undo changes for migration


-- ADD DEFAULT CURRENT_TIMESTAMP again

ALTER TABLE ingrid_anniversary MODIFY fetched TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ingrid_cms MODIFY item_changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ingrid_cms_item MODIFY item_changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ingrid_lookup MODIFY item_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ingrid_newsletter_data MODIFY created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ingrid_principal_pref MODIFY modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ingrid_rss_source MODIFY lastUpdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE ingrid_rss_store MODIFY published_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE ingrid_tiny_url MODIFY tiny_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
