/*
 * **************************************************-
 * Ingrid Portal Apps
 * ==================================================
 * Copyright (C) 2014 wemove digital solutions GmbH
 * ==================================================
 * Licensed under the EUPL, Version 1.1 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 * 
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl5
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * **************************************************#
 */
({"lightsteelblue":"淡�?��?色","orangered":"橙紅色","midnightblue":"�?�夜�?","cadetblue":"�?�?�?","seashell":"海�?色","slategrey":"岩�?�色","coral":"�?�瑚紅","darkturquoise":"暗�?�石綠","antiquewhite":"米白色","mediumspringgreen":"中春綠色","salmon":"鮭紅色","darkgrey":"暗�?�色","ivory":"象牙色","greenyellow":"綠黃色","mistyrose":"霧玫瑰色","lightsalmon":"淡鮭紅","silver":"銀色","dimgrey":"�?�?�色","orange":"橙色","white":"白色","navajowhite":"�?�地安黃色","royalblue":"�?�?色","deeppink":"深粉紅色","lime":"檸檬色","oldlace":"舊蕾絲色","chartreuse":"淡黃綠色","darkcyan":"暗�?�色","yellow":"黃色","linen":"亞麻色","olive":"橄欖色","gold":"金色","lawngreen":"�?�綠色","lightyellow":"淡黃色","tan":"皮�?�色","darkviolet":"暗紫羅蘭色","lightslategrey":"淡岩�?�色","grey":"�?�色","darkkhaki":"暗�?�其色","green":"綠色","deepskyblue":"深天�?色","aqua":"水色","sienna":"黃土赭色","mintcream":"薄�?�乳白色","rosybrown":"玫瑰�?","mediumslateblue":"中岩�?色","magenta":"紫紅色","lightseagreen":"淡海綠色","cyan":"�?�色","olivedrab":"橄欖綠","darkgoldenrod":"暗金�?�色","slateblue":"岩�?色","mediumaquamarine":"中碧綠色","lavender":"薰衣�?�紫","mediumseagreen":"中海綠色","maroon":"栗色","darkslategray":"暗岩�?�色","mediumturquoise":"中�?�石綠","ghostwhite":"幽�?�色","darkblue":"暗�?色","mediumvioletred":"中紫羅蘭紅","brown":"�?色","lightgray":"淡�?�色","sandybrown":"沙�?色","pink":"粉紅色","firebrick":"紅磚色","indigo":"�?��?色","snow":"雪白色","darkorchid":"暗蘭花色","turquoise":"�?�石綠","chocolate":"巧克力色","springgreen":"春綠色","moccasin":"鹿皮黃色","navy":"海�?�?","lemonchiffon":"奶油黃","teal":"深�?綠色","floralwhite":"花�?�白","cornflowerblue":"矢車�?��?","paleturquoise":"�?��?�石綠","purple":"紫色","gainsboro":"石�?��?�","plum":"�?�紫色","red":"紅色","blue":"�?色","forestgreen":"森綠色","darkgreen":"暗綠色","honeydew":"密瓜色","darkseagreen":"暗海綠色","lightcoral":"淡�?�瑚紅","palevioletred":"�?�紫羅蘭紅","mediumpurple":"中紫色","saddlebrown":"�?�?色","darkmagenta":"暗紫紅色","thistle":"薊色","whitesmoke":"白煙色","wheat":"�?麥色","violet":"紫羅蘭色","lightskyblue":"淡天�?色","goldenrod":"金�?�色","mediumblue":"中�?色","skyblue":"天�?色","crimson":"暗深紅色","darksalmon":"暗鮭紅","darkred":"暗紅色","darkslategrey":"暗岩�?�色","peru":"祕魯色","lightgrey":"淡�?�色","lightgoldenrodyellow":"淡金�?�黃","blanchedalmond":"�??�?白","aliceblue":"愛麗絲�?","bisque":"橘黃色","slategray":"岩�?�色","palegoldenrod":"�?�金�?�色","darkorange":"暗橙色","aquamarine":"碧綠色","lightgreen":"淡綠色","burlywood":"實木色","dodgerblue":"�?�奇�?","darkgray":"暗�?�色","lightcyan":"淡�?�色","powderblue":"粉�?色","blueviolet":"�?紫色","orchid":"蘭花色","dimgray":"�?�?�色","beige":"�?�棕色","fuchsia":"海棠紅","lavenderblush":"薰衣�?�紫紅","hotpink":"暖粉紅色","steelblue":"�?��?色","tomato":"蕃茄紅","lightpink":"淡粉紅色","limegreen":"檸檬綠","indianred":"�?�度紅","papayawhip":"番木瓜色","lightslategray":"淡岩�?�色","gray":"�?�色","mediumorchid":"中蘭紫色","cornsilk":"玉米黃","black":"黑色","seagreen":"海綠色","darkslateblue":"暗岩�?色","khaki":"�?�其色","lightblue":"淡�?色","palegreen":"�?�綠色","azure":"天�?色","peachpuff":"粉撲桃色","darkolivegreen":"暗橄欖綠","yellowgreen":"黃綠色"})