--
-- Daten für Tabelle `help_messages`
--

UPDATE `info` SET `value_name` = '3.6.2' WHERE  `info`.`key_name` = 'version';

-- Updated stuff for InGrid 3.6.1
-- ==============================

DELETE FROM help_messages WHERE gui_id = 3225;
DELETE FROM help_messages WHERE gui_id = 6000;
DELETE FROM help_messages WHERE gui_id = 7004;
DELETE FROM help_messages WHERE gui_id = 10025;
DELETE FROM help_messages WHERE gui_id = 10026;
DELETE FROM help_messages WHERE gui_id = 10027;
DELETE FROM help_messages WHERE gui_id = 10200;
DELETE FROM help_messages WHERE gui_id = 10201;
INSERT INTO `help_messages` (`id`, `version`, `gui_id`, `entity_class`, `language`, `name`, `help_text`, `sample`) VALUES
(1422, 0, 3225, -1, 'de', 'Als ATOM-Download Dienst bereitstellen', '<p>Bei aktivierter Option, wird dieser Datensatz im Portal als Download angeboten. Zusätzlich wird die in den Katalogeinstellungen hinterlegte "ATOM-Downloadservice-URL" automatisch ins ISO-Format unter "distributionInfo/*/linkage" abgebildet.</p><p>Bei ATOM-Downloaddiensten, die im Rahmen von INSPIRE bereitgestellt und nicht über den InGridEditor generiert werden, ist als Operation "Get Download Service Metadata" auszuwählen.</p>', ''),
(1423, 0, 3225, -1, 'en', 'Provide as ATOM-download service', '<p>If checked, this metadata will be available as a download in the portal. Additionally the "ATOM-Downloadservice-URL" from the catalog settings will be added automatically to the ISO-format under "distributionInfo/*/linkage".</p><p>ATOM-download services, which are provided by INSPIRE and not generated by the InGridEditor, the operation "Get Download Service Metadata" needs to be added.</p>', ''),
(369, 0, 6000, -1, 'de', 'INSPIRE-relevanter Datensatz', '<p>Dieses Feld definiert, wenn aktiviert, dass ein Metadatensatz für das INSPIRE-Monitoring vorgesehen ist.</p><p>Folgende Eigenschaften ändern sich bei Aktivierung:</p><ul><li>Hinzufügen des Schlagwortes "inspireidentifiziert" bei ISO XML Generierung</li><li>verpflichtende Angabe eines INSPIRE Themas bei Klasse Informationssystem (6)</li><li>WebServices wird als Defaultwert für die unterstützte Plattform bei einer neuen Operation verwendet</li></ul>', ''),
(1369, 0, 6000, -1, 'en', 'INSPIRE-relevant Record', '<p>If clicked, this record is relevant for INSPIRE-Monitoring.</p><p>The following properties change, when activated:</p><ul><li>Adding of the keyword "inspireidentifiziert" during ISO XML generation</li><li>INSPIRE topic becomes a mandatory field for class information system (6)</li><li>WebServices will be default value for the supported platform when adding a new operation</li></ul>', ''),
(152, 0, 7004, -1, 'de', 'Verfügbarkeit', 'Angabe, ob und in welcher Form es Zugriffsbeschränkungen oder Nutzungsbedingungen gibt', ''),
(320, 0, 10025, -1, 'de', 'Zugriffsbeschränkungen', 'Das Feld „Zugriffsbeschränkungen“ beschreibt, die Art der Zugriffsbeschränkung. Bei frei nutzbaren Daten bzw. Services soll der Eintrag „keine“ ausgewählt werden. Sind die Beschränkungen unbekannt, soll der Eintrag „unbekannt" eingetragen werden (ISO: accessConstraints).', ''),
(322, 0, 10026, -1, 'de', 'Anwendungseinschränkungen', 'Einschränkungen, die die Eignung der Ressource oder Metadaten betreffen (ISO: useLimitation)', 'nicht für Navigationszwecke geeignet'),
(1530, 0, 10027, -1, 'de', 'Nutzungsbedingungen', 'Einschränkungen zum Schutz der Privatsphäre oder des geistigen Eigentums sowie andere besondere Einschränkungen oder Warnungen bezüglich der Nutzung der Ressource oder der Metadaten (ISO: useConstraints)', ''),
(1500, 0, 10200, -1, 'de', 'Erfassungsassistent - Anwendungseinschränkungen', 'Auswahl, ob die Anwendungseinschränkungen für ein neues Datenobjekt übernommen werden sollen.', ''),
(1502, 0, 10201, -1, 'de', 'Erfassungsassistent - Zugriffsbeschränkungen', 'Auswahl, welche der Zugriffsbeschränkungen übernommen werden sollen. Durch einen Klick in die erste Spalte der Tabelle, kann über eine Checkbox der zu übernehmende Eintrag ausgewählt werden.', '');