--
-- Daten für Tabelle help_messages
--

UPDATE info SET value_name = '3.6.2' WHERE  info.key_name = 'version';

-- Updated stuff for InGrid 3.6.2
-- ==============================

DELETE FROM help_messages WHERE gui_id = 3225;
DELETE FROM help_messages WHERE gui_id = 6000;
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(1422, 0, 3225, -1, 'de', 'Als ATOM-Download Dienst bereitstellen', '<p>Bei aktivierter Option, wird dieser Datensatz im Portal als Download angeboten. Zusätzlich wird die in den Katalogeinstellungen hinterlegte "ATOM-Downloadservice-URL" automatisch ins ISO-Format unter "distributionInfo/*/linkage" abgebildet.</p><p>Bei ATOM-Downloaddiensten, die im Rahmen von INSPIRE bereitgestellt und nicht über den InGridEditor generiert werden, ist als Operation "Get Download Service Metadata" auszuwählen.</p>', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(1423, 0, 3225, -1, 'en', 'Provide as ATOM-download service', '<p>If checked, this metadata will be available as a download in the portal. Additionally the "ATOM-Downloadservice-URL" from the catalog settings will be added automatically to the ISO-format under "distributionInfo/*/linkage".</p><p>ATOM-download services, which are provided by INSPIRE and not generated by the InGridEditor, the operation "Get Download Service Metadata" needs to be added.</p>', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(369, 0, 6000, -1, 'de', 'INSPIRE-relevanter Datensatz', '<p>Dieses Feld definiert, wenn aktiviert, dass ein Metadatensatz für das INSPIRE-Monitoring vorgesehen ist.</p><p>Folgende Eigenschaften ändern sich bei Aktivierung:</p><ul><li>Hinzufügen des Schlagwortes "inspireidentifiziert" bei ISO XML Generierung</li><li>verpflichtende Angabe eines INSPIRE Themas bei Klasse Informationssystem (6)</li><li>WebServices wird als Defaultwert für die unterstützte Plattform bei einer neuen Operation verwendet</li></ul>', '');
INSERT INTO help_messages (id, version, gui_id, entity_class, language, name, help_text, sample) VALUES
(1369, 0, 6000, -1, 'en', 'INSPIRE-relevant Record', '<p>If clicked, this record is relevant for INSPIRE-Monitoring.</p><p>The following properties change, when activated:</p><ul><li>Adding of the keyword "inspireidentifiziert" during ISO XML generation</li><li>INSPIRE topic becomes a mandatory field for class information system (6)</li><li>WebServices will be default value for the supported platform when adding a new operation</li></ul>', '');