INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (1, 'bund', 'Bund', 1);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (2, 'bw', 'Baden-Württemberg', 2);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (3, 'by', 'Bayern', 3);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (4, 'be', 'Berlin', 4);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (5, 'bb', 'Brandenburg', 5);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (6, 'hb', 'Bremen', 6);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (7, 'hh', 'Hamburg', 7);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (8, 'he', 'Hessen', 8);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (9, 'mv', 'Mecklenburg-Vorpommern', 9);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (10, 'ni', 'Niedersachsen', 10);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (11, 'nw', 'Nordrhein-Westfalen', 11);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (12, 'rp', 'Rheinland-Pfalz', 12);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (13, 'sl', 'Saarland', 13);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (14, 'sn', 'Sachsen', 14);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (15, 'st', 'Sachsen-Anhalt', 15);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (16, 'sh', 'Schleswig-Holstein', 16);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (17, 'th', 'Thüringen', 17);

INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (1, 'bb_mluv', 'Ministerium für Ländliche Entwicklung, Umwelt und Verbraucherschutz des Landes Brandenburg', 1);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (2, 'be_senst', 'Senatsverwaltung für Stadtentwicklung', 2);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (3, 'be_snb', 'Stiftung Naturschutz Berlin', 3);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (4, 'bu_blauerengel', 'RAL/Umweltbundesamt Umweltzeichen "Blauer Engel"', 4);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (5, 'bu_aa', 'Auswärtiges Amt', 5);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (6, 'bu_agenda', 'Agenda-Transfer. Agentur für Nachhaltigkeit GmbH', 6);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (7, 'bu_bfg', 'Bundesanstalt für Gewässerkunde', 7);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (8, 'bu_bfn', 'Bundesamt für Naturschutz', 8);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (9, 'bu_bfr', 'Bundesinstitut für Risikobewertung', 9);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (10, 'bu_bfs', 'Bundesamt für Strahlenschutz', 10);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (11, 'bu_bgr', 'Bundesanstalt für Geowissenschaften und Rohstoffe', 11);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (12, 'bu_bka', 'Bundeskriminalamt', 12);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (13, 'bu_bmbf', 'Bundesministerium für Bildung und Forschung', 13);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (14, 'bu_bmevl', 'Bundesministerium für Ernährung, Landwirtschaft und Verbraucherschutz', 14);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (15, 'bu_bmf', 'Bundesministerium der Finanzen', 15);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (16, 'bu_bmu', 'Bundesministerium für Umwelt, Naturschutz und Reaktorsicherheit', 16);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (17, 'bu_bmz', 'Bundesministerium für wirtschaftliche Zusammenarbeit und Entwicklung', 17);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (18, 'bu_bpa', 'Presse- und Informationsamt der Bundesregierung', 18);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (19, 'bu_bpb', 'Bundeszentrale für politische Bildung', 19);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (20, 'bu_bsh', 'Bundesamt für Seeschifffahrt und Hydrographie', 20);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (21, 'bu_bvl', 'Bundesamt für Verbraucherschutz und Lebensmittelsicherheit', 21);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (22, 'bu_destatis', 'Statistisches Bundesamt', 22);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (23, 'bu_dlr', 'Deutsches Zentrum für Luft- und Raumfahrt DLR e.V.', 23);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (24, 'bu_dwd', 'Deutscher Wetterdienst', 24);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (25, 'bu_gein', 'gein Information Broker (Webseiten aller Informationsanbieter)', 25);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (26, 'bu_gtz', 'Deutsche Gesellschaft für Technische Zusammenarbeit (GTZ) GmbH', 26);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (27, 'bu_kug', 'Koordinierungsstelle UDK/GEIN', 27);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (28, 'bu_labo', 'Länderarbeitsgemeinschaft Boden LABO', 28);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (29, 'bu_laofdh', 'Leitstelle des Bundes für Abwassertechnik, Boden- und Grundwasserschutz, Kampfmittelräumung und das Liegenschaftsinformationssystem Außenanlagen LISA', 29);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (30, 'bu_lawa', 'Länderarbeitsgemeinschaft Wasser', 30);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (31, 'bu_nokis', 'Bundesanstalt für Wasserbau - Dienststelle Hamburg', 31);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (32, 'bu_rki', 'Robert-Koch-Institut', 32);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (33, 'bu_sru', 'Rat von Sachverständigen für Umweltfragen (SRU)', 33);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (34, 'bu_ssk', 'Strahlenschutzkommission', 34);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (35, 'bu_uba', 'Umweltbundesamt', 35);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (36, 'bu_udk', 'Umweltdatenkatalog', 36);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (37, 'bu_umk', 'Umweltministerkonferenz', 37);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (38, 'bu_wbgu', 'Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen - WBGU', 38);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (39, 'bu_bfn', 'Bundesamt für Naturschutz', 39);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (40, 'bw_gaa', 'Staatliche Gewerbeaufsicht Baden-Württemberg', 40);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (41, 'bw_lel', 'Informationsdienst der Landwirtschaftsverwaltung Baden-Württemberg', 41);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (42, 'bw_lgrb', 'Landesamt für Geologie, Rohstoffe und Bergbau Baden-Württemberg', 42);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (43, 'bw_lu', 'Landesanstalt für Umwelt, Messungen und Naturschutz Baden-Württemberg', 43);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (44, 'bw_lvm', 'Landesvermessungsamt Baden-Württemberg', 44);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (45, 'bw_mlr', 'Ministerium für Ernährung und Ländlichen Raum', 45);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (46, 'bw_um', 'Umweltministerium Baden-Württemberg', 46);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (47, 'bw_mi', 'Innenministerium Baden-Württemberg', 47);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (48, 'by_brrhoen', 'Biosphärenreservat Rhön', 48);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (49, 'by_gla', 'Bayerisches Geologisches Landesamt', 49);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (50, 'by_lfstad', 'Bayerisches Landesamt für Statistik und Datenverarbeitung', 50);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (51, 'by_lfu', 'Bayerisches Landesamt für Umweltschutz', 51);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (52, 'by_lfw', 'Bayerisches Landesamt für Wasserwirtschaft', 52);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (53, 'by_npbayw', 'Nationalpark Bayerischer Wald', 53);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (54, 'by_npbg', 'Nationalpark Berchtesgaden', 54);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (55, 'by_sugv', 'Bayerisches Staatsministerium für Umwelt, Gesundheit und Verbraucherschutz', 55);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (56, 'hb_sbu', 'Senator für Bau und Umwelt Bremen', 56);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (57, 'he_hlug', 'Hessisches Landesamt für Umwelt und Geologie', 57);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (58, 'he_hmulv', 'Hessisches Ministerium für Umwelt, ländlichen Raum und Verbraucherschutz', 58);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (59, 'he_umwelt', 'Umweltatlas Hessen', 59);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (60, 'hh_argeelbe', 'Arbeitsgemeinschaft für die Reinhaltung der Elbe', 60);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (61, 'hh_su', 'Behörde für Stadtentwicklung und Umwelt', 61);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (62, 'hh_wa', 'Behörde für Wirtschaft und Arbeit', 62);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (63, 'mv_lfg', 'Landesamt für Forsten und Großschutzgebiete', 63);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (64, 'mv_lung', 'Landesamt für Umwelt, Naturschutz und Geologie Mecklenburg-Vorpommern (LUNG)', 64);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (65, 'mv_npmueritz', 'Nationalparkamt Müritz', 65);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (66, 'mv_nvblmv', 'Nationalparkamt Vorpommersche Boddenlandschaft', 66);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (67, 'mv_schaalsee', 'Amt für das Biosphärenreservat Schaalsee', 67);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (68, 'mv_sm', 'Sozialministerium Mecklenburg-Vorpommern', 68);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (69, 'mv_um', 'Umweltministerium Mecklenburg-Vorpommern', 69);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (70, 'ni_gaa', 'Niedersächsische Gewerbeaufsicht', 70);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (71, 'ni_laves', 'Niedersächsisches Landesamt für Verbraucherschutz und Lebensmittelsicherheit', 71);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (72, 'ni_lbeg', 'Landesamt für Bergbau, Energie und Geologie', 72);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (73, 'ni_lwkh', 'Landwirtschaftskammer Hannover', 73);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (74, 'ni_ms', 'Niedersächsisches Ministerium für Soziales, Frauen, Familie und Gesundheit', 74);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (75, 'ni_mu', 'Niedersächsisches Umweltministerium', 75);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (76, 'ni_nls', 'Niedersächsisches Landesamt für Statistik', 76);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (77, 'ni_nlwkn', 'Niedersächsischer Landesbetrieb für Wasserwirtschaft, Küsten- und Naturschutz', 77);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (78, 'ni_nna', 'Alfred Toepfer Akademie für Naturschutz', 78);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (79, 'ni_npharz', 'Nationalparkverwaltung Harz', 79);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (80, 'ni_npwatt', 'Nationalpark Wattenmeer', 80);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (81, 'ni_ml', 'Niedersächsisches Ministerium für den ländlichen Raum, Ernährung, Landwirtschaft und Verbraucherschutz', 81);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (82, 'ni_lga', 'Niedersächsisches Landesgesundheitsamt', 82);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (83, 'ni_mw', 'Niedersächsisches Ministerium für Wirtschaft, Arbeit und Verkehr', 83);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (84, 'ni_sbv', 'Niedersächsische Landesbehörde für Straßenbau und Verkehr', 84);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (85, 'ni_mi', 'Niedersächsisches Ministerium für Inneres und Sport', 85);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (86, 'nw_gdnw', 'Geologischer Dienst Nordrhein-Westfalen', 86);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (87, 'nw_loebf', 'Landesanstalt für Ökologie, Bodenordnung und Forsten des Landes Nordrhein-Westfalen (LÖBF)', 87);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (88, 'nw_lua', 'Landesumweltamt NRW', 88);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (89, 'nw_munlv', 'Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz des Landes Nordrhein-Westfalen', 89);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (90, 'nw_stuaha', 'Staatliches Umweltamt Hagen', 90);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (91, 'nw_stualp', 'Staatliches Umweltamt Lippstadt', 91);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (92, 'rp_hmz', 'Landesamt für Wasserwirtschaft Rheinland-Pfalz', 92);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (93, 'rp_lfug', 'Landesamt für Umweltschutz und Gewerbeaufsicht', 93);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (94, 'rp_lzu', 'Landeszentrale für Umweltaufklärung', 94);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (95, 'rp_forst', 'Landesforstverwaltung Rheinland-Pfalz', 95);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (96, 'rp_muf', 'Ministerium für Umwelt und Forsten des Landes Rheinland-Pfalz', 96);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (97, 'sh_kfue', 'Kernreaktorfernüberwachung Schleswig-Holstein', 97);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (98, 'sh_lanu', 'Landesamt für Natur und Umwelt', 98);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (99, 'sh_luesh', 'Lufthygienische Überwachung Schleswig-Holstein', 99);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (100, 'sh_munl', 'Ministerium für Umwelt, Naturschutz und Landwirtschaft', 100);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (101, 'sh_npa', 'Nationalpark Schleswig-Holsteinisches Wattenmeer', 101);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (102, 'sh_umweltaka', 'Akademie für Natur und Umwelt des Landes Schleswig-Holstein', 102);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (103, 'sl_mfu', 'Ministerium für Umwelt', 103);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (104, 'sn_lfug', 'Sächsisches Landesamt für Umwelt und Geologie', 104);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (105, 'sn_smul', 'Staatsministerium für Umwelt und Landwirtschaft', 105);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (106, 'st_lau', 'Landesamt für Umweltschutz Sachsen-Anhalt', 106);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (107, 'st_lue', 'Luftüberwachungssystem Sachsen-Anhalt', 107);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (108, 'st_mlu', 'Ministerium für Landwirtschaft und Umwelt', 108);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (109, 'th_tlug', 'Thüringer Landesanstalt für Umwelt und Geologie', 109);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (110, 'th_tmlnu', 'Thüringer Ministerium für Landwirtschaft, Naturschutz und Umwelt', 110);

INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (1, 'abf', 'abfall', 1);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (2, 'alt', 'altlasten', 2);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (3, 'bau', 'bauen', 3);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (4, 'bod', 'boden', 4);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (5, 'che', 'chemikalien', 5);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (6, 'ene', 'energie', 6);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (7, 'for', 'forstwirtschaft', 7);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (8, 'gen', 'gentechnik', 8);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (9, 'geo', 'geologie', 9);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (10, 'ges', 'gesundheit', 10);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (11, 'lae', 'laermerschuetterung', 11);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (12, 'lan', 'landwirtschaft', 12);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (13, 'luf', 'luftklima', 13);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (14, 'nac', 'nachhaltigeentwicklung', 14);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (15, 'nat', 'naturlandschaft', 15);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (16, 'str', 'strahlung', 16);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (17, 'tie', 'tierschutz', 17);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (18, 'uin', 'umweltinformation', 18);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (19, 'uwi', 'umweltwirtschaft', 19);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (20, 'ver', 'verkehr', 20);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (21, 'was', 'wasser', 21);

INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (1, 'rec', 'rechtliches', 1);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (2, 'kon', 'konzeptionelles', 2);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (3, 'sta', 'statusberichte', 3);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (4, 'umw', 'umweltzustand', 4);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (5, 'dat', 'datenkarten', 5);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (6, 'ris', 'risikobewertungen', 6);

INSERT INTO ingrid_service_rubric (id, form_value, query_value, sortkey) VALUES (1, 'pre', 'press', 1);
INSERT INTO ingrid_service_rubric (id, form_value, query_value, sortkey) VALUES (2, 'pub', 'publication', 2);
INSERT INTO ingrid_service_rubric (id, form_value, query_value, sortkey) VALUES (3, 'ver', 'event', 3);

INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (1, 'str', 'radiation', 1);
INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (2, 'luf', 'air', 2);
INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (3, 'was', 'water', 3);
INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (4, 'wei', 'misc', 4);

INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (1, 'ini', 'initiative', 1);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (2, 'his', 'historical', 2);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (3, 'law', 'law', 3);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (4, 'ins', 'institution', 4);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (5, 'dis', 'disaster', 5);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (6, 'cfe', 'conference', 6);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (7, 'cve', 'convention', 7);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (8, 'yea', 'ofTheYear', 8);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (9, 'pub', 'publication', 9);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (10, 'gui', 'guideline', 10);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (11, 'mar', 'marineAccident', 11);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (12, 'ind', 'industrialAccident', 12);

INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (1, 'UBA', 'RSS-UBA', 'http://www.uba.de/rss/ubapresseinfo.xml', 'de');
INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (2, 'BFN', 'BFN-UBA', 'http://www.bfn.de/6.100.html', 'de');
INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (3, 'MUF RLP', 'MUF RLP', 'http://www.muf.rlp.de/rss/rss_1_20.xml', 'de');
INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (4, 'BFN', 'BfN-Skripten', 'http://www.bfn.de/rss/skripten.xml', 'de');

INSERT INTO PRINCIPAL_RULE_ASSOC VALUES ('admin', 'page', 'role-fallback');
INSERT INTO SECURITY_CREDENTIAL VALUES(1,1,'admin',0,'org.apache.jetspeed.security.spi.impl.DefaultPasswordCredentialImpl',0,0,1,0,0,'2004-05-22 16:27:12.572','2004-05-22 16:27:12.572',null,null,null);

INSERT INTO groups VALUES('admin');
INSERT INTO groups VALUES('manager');
INSERT INTO groups VALUES('user');
INSERT INTO roles VALUES('admin');
INSERT INTO roles VALUES('manager');
INSERT INTO roles VALUES('user');
INSERT INTO usergrouprole VALUES(1,'admin','admin','admin');
INSERT INTO usergrouprole VALUES(2,'admin','admin','manager');
INSERT INTO usergrouprole VALUES(3,'admin','admin','user');
INSERT INTO users VALUES('admin','admin');
INSERT INTO users VALUES('guest','guest');

INSERT INTO ingrid_help_structure VALUES (1, 0, 'index', 1);
INSERT INTO ingrid_help_structure VALUES (2, 1, NULL, 1);
INSERT INTO ingrid_help_content VALUES (1, 1, 'de', 'Hilfe zu PortalU', NULL);
INSERT INTO ingrid_help_content VALUES (2, 2, 'de', 'Hilfethemen', '<ul>\r\n<li>Über PortalU</li>\r\n<li>Suche</li>\r\n<li>Umweltthemen</li>\r\n<li>Service</li>\r\n<li>Messwerte</li>\r\n<li>Umweltchronik</li>\r\n<li>Karten</li>\r\n<li>Aktuelles</li>\r\n<li>PortalU informiert</li>\r\n<li>Mein PortalU</li>\r\n<li>Newsletter</li>\r\n</ul>');
