INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (1, 'bund', 'Bund', 1);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (2, 'bw', 'Baden-Württemberg', 2);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (3, 'by', 'Bayern', 3);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (4, 'be', 'Berlin', 4);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (5, 'bb', 'Brandenburg', 5);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (6, 'hb', 'Bremen', 6);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (7, 'hh', 'Hamburg', 7);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (8, 'he', 'Hessen', 8);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (9, 'mv', 'Mecklenburg-Vorpommern', 9);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (10, 'ni', 'Niedersachsen', 10);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (11, 'nw', 'Nordrhein-Westfalen', 11);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (12, 'rp', 'Rheinland-Pfalz', 12);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (13, 'sl', 'Saarland', 13);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (14, 'sn', 'Sachsen', 14);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (15, 'st', 'Sachsen-Anhalt', 15);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (16, 'sh', 'Schleswig-Holstein', 16);
INSERT INTO ingrid_partner (id, ident, name, sortkey) VALUES (17, 'th', 'Thüringen', 17);

INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (1, 'bb_mluv', 'Ministerium für Ländliche Entwicklung, Umwelt und Verbraucherschutz des Landes Brandenburg', 1);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (2, 'be_senst', 'Senatsverwaltung für Stadtentwicklung', 2);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (3, 'be_snb', 'Stiftung Naturschutz Berlin', 3);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (4, 'bu_blauerengel', 'RAL/Umweltbundesamt Umweltzeichen "Blauer Engel"', 4);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (5, 'bu_aa', 'Auswärtiges Amt', 5);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (6, 'bu_agenda', 'Agenda-Transfer. Agentur für Nachhaltigkeit GmbH', 6);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (7, 'bu_bfg', 'Bundesanstalt für Gewässerkunde', 7);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (8, 'bu_bfn', 'Bundesamt für Naturschutz', 8);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (9, 'bu_bfr', 'Bundesinstitut für Risikobewertung', 9);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (10, 'bu_bfs', 'Bundesamt für Strahlenschutz', 10);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (11, 'bu_bgr', 'Bundesanstalt für Geowissenschaften und Rohstoffe', 11);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (12, 'bu_bka', 'Bundeskriminalamt', 12);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (13, 'bu_bmbf', 'Bundesministerium für Bildung und Forschung', 13);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (14, 'bu_bmevl', 'Bundesministerium für Ernährung, Landwirtschaft und Verbraucherschutz', 14);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (15, 'bu_bmf', 'Bundesministerium der Finanzen', 15);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (16, 'bu_bmu', 'Bundesministerium für Umwelt, Naturschutz und Reaktorsicherheit', 16);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (17, 'bu_bmz', 'Bundesministerium für wirtschaftliche Zusammenarbeit und Entwicklung', 17);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (18, 'bu_bpa', 'Presse- und Informationsamt der Bundesregierung', 18);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (19, 'bu_bpb', 'Bundeszentrale für politische Bildung', 19);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (20, 'bu_bsh', 'Bundesamt für Seeschifffahrt und Hydrographie', 20);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (21, 'bu_bvl', 'Bundesamt für Verbraucherschutz und Lebensmittelsicherheit', 21);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (22, 'bu_destatis', 'Statistisches Bundesamt', 22);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (23, 'bu_dlr', 'Deutsches Zentrum für Luft- und Raumfahrt DLR e.V.', 23);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (24, 'bu_dwd', 'Deutscher Wetterdienst', 24);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (25, 'bu_gein', 'PortalU Information Broker (Webseiten aller Informationsanbieter)', 25);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (26, 'bu_gtz', 'Deutsche Gesellschaft für Technische Zusammenarbeit (GTZ) GmbH', 26);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (27, 'bu_kug', 'Koordinierungsstelle PortlaU', 27);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (28, 'bu_labo', 'Länderarbeitsgemeinschaft Boden LABO', 28);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (29, 'bu_laofdh', 'Leitstelle des Bundes für Abwassertechnik, Boden- und Grundwasserschutz, Kampfmittelräumung und das Liegenschaftsinformationssystem Außenanlagen LISA', 29);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (30, 'bu_lawa', 'Länderarbeitsgemeinschaft Wasser', 30);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (31, 'bu_nokis', 'Bundesanstalt für Wasserbau - Dienststelle Hamburg', 31);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (32, 'bu_rki', 'Robert-Koch-Institut', 32);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (33, 'bu_sru', 'Rat von Sachverständigen für Umweltfragen (SRU)', 33);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (34, 'bu_ssk', 'Strahlenschutzkommission', 34);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (35, 'bu_uba', 'Umweltbundesamt', 35);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (36, 'bu_udk', 'Umweltdatenkatalog', 36);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (37, 'bu_umk', 'Umweltministerkonferenz', 37);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (38, 'bu_wbgu', 'Wissenschaftlicher Beirat der Bundesregierung Globale Umweltveränderungen - WBGU', 38);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (39, 'bu_bfn', 'Bundesamt für Naturschutz', 39);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (40, 'bw_gaa', 'Staatliche Gewerbeaufsicht Baden-Württemberg', 40);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (41, 'bw_lel', 'Informationsdienst der Landwirtschaftsverwaltung Baden-Württemberg', 41);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (42, 'bw_lgrb', 'Landesamt für Geologie, Rohstoffe und Bergbau Baden-Württemberg', 42);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (43, 'bw_lu', 'Landesanstalt für Umwelt, Messungen und Naturschutz Baden-Württemberg', 43);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (44, 'bw_lvm', 'Landesvermessungsamt Baden-Württemberg', 44);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (45, 'bw_mlr', 'Ministerium für Ernährung und Ländlichen Raum', 45);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (46, 'bw_um', 'Umweltministerium Baden-Württemberg', 46);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (47, 'bw_mi', 'Innenministerium Baden-Württemberg', 47);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (48, 'by_brrhoen', 'Biosphärenreservat Rhön', 48);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (49, 'by_gla', 'Bayerisches Geologisches Landesamt', 49);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (50, 'by_lfstad', 'Bayerisches Landesamt für Statistik und Datenverarbeitung', 50);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (51, 'by_lfu', 'Bayerisches Landesamt für Umweltschutz', 51);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (52, 'by_lfw', 'Bayerisches Landesamt für Wasserwirtschaft', 52);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (53, 'by_npbayw', 'Nationalpark Bayerischer Wald', 53);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (54, 'by_npbg', 'Nationalpark Berchtesgaden', 54);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (55, 'by_sugv', 'Bayerisches Staatsministerium für Umwelt, Gesundheit und Verbraucherschutz', 55);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (56, 'hb_sbu', 'Senator für Bau und Umwelt Bremen', 56);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (57, 'he_hlug', 'Hessisches Landesamt für Umwelt und Geologie', 57);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (58, 'he_hmulv', 'Hessisches Ministerium für Umwelt, ländlichen Raum und Verbraucherschutz', 58);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (59, 'he_umwelt', 'Umweltatlas Hessen', 59);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (60, 'hh_argeelbe', 'Arbeitsgemeinschaft für die Reinhaltung der Elbe', 60);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (61, 'hh_su', 'Behörde für Stadtentwicklung und Umwelt', 61);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (62, 'hh_wa', 'Behörde für Wirtschaft und Arbeit', 62);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (63, 'mv_lfg', 'Landesamt für Forsten und Großschutzgebiete', 63);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (64, 'mv_lung', 'Landesamt für Umwelt, Naturschutz und Geologie Mecklenburg-Vorpommern (LUNG)', 64);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (65, 'mv_npmueritz', 'Nationalparkamt Müritz', 65);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (66, 'mv_nvblmv', 'Nationalparkamt Vorpommersche Boddenlandschaft', 66);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (67, 'mv_schaalsee', 'Amt für das Biosphärenreservat Schaalsee', 67);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (68, 'mv_sm', 'Sozialministerium Mecklenburg-Vorpommern', 68);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (69, 'mv_um', 'Umweltministerium Mecklenburg-Vorpommern', 69);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (70, 'ni_gaa', 'Niedersächsische Gewerbeaufsicht', 70);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (71, 'ni_laves', 'Niedersächsisches Landesamt für Verbraucherschutz und Lebensmittelsicherheit', 71);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (72, 'ni_lbeg', 'Landesamt für Bergbau, Energie und Geologie', 72);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (73, 'ni_lwkh', 'Landwirtschaftskammer Hannover', 73);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (74, 'ni_ms', 'Niedersächsisches Ministerium für Soziales, Frauen, Familie und Gesundheit', 74);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (75, 'ni_mu', 'Niedersächsisches Umweltministerium', 75);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (76, 'ni_nls', 'Niedersächsisches Landesamt für Statistik', 76);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (77, 'ni_nlwkn', 'Niedersächsischer Landesbetrieb für Wasserwirtschaft, Küsten- und Naturschutz', 77);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (78, 'ni_nna', 'Alfred Toepfer Akademie für Naturschutz', 78);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (79, 'ni_npharz', 'Nationalparkverwaltung Harz', 79);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (80, 'ni_npwatt', 'Nationalpark Wattenmeer', 80);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (81, 'ni_ml', 'Niedersächsisches Ministerium für den ländlichen Raum, Ernährung, Landwirtschaft und Verbraucherschutz', 81);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (82, 'ni_lga', 'Niedersächsisches Landesgesundheitsamt', 82);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (83, 'ni_mw', 'Niedersächsisches Ministerium für Wirtschaft, Arbeit und Verkehr', 83);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (84, 'ni_sbv', 'Niedersächsische Landesbehörde für Straßenbau und Verkehr', 84);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (85, 'ni_mi', 'Niedersächsisches Ministerium für Inneres und Sport', 85);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (86, 'nw_gdnw', 'Geologischer Dienst Nordrhein-Westfalen', 86);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (87, 'nw_loebf', 'Landesanstalt für Ökologie, Bodenordnung und Forsten des Landes Nordrhein-Westfalen (LÖBF)', 87);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (88, 'nw_lua', 'Landesumweltamt NRW', 88);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (89, 'nw_munlv', 'Ministerium für Umwelt und Naturschutz, Landwirtschaft und Verbraucherschutz des Landes Nordrhein-Westfalen', 89);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (90, 'nw_stuaha', 'Staatliches Umweltamt Hagen', 90);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (91, 'nw_stualp', 'Staatliches Umweltamt Lippstadt', 91);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (92, 'rp_hmz', 'Landesamt für Wasserwirtschaft Rheinland-Pfalz', 92);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (93, 'rp_lfug', 'Landesamt für Umweltschutz und Gewerbeaufsicht', 93);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (94, 'rp_lzu', 'Landeszentrale für Umweltaufklärung', 94);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (95, 'rp_forst', 'Landesforstverwaltung Rheinland-Pfalz', 95);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (96, 'rp_muf', 'Ministerium für Umwelt und Forsten des Landes Rheinland-Pfalz', 96);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (97, 'sh_kfue', 'Kernreaktorfernüberwachung Schleswig-Holstein', 97);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (98, 'sh_lanu', 'Landesamt für Natur und Umwelt', 98);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (99, 'sh_luesh', 'Lufthygienische Überwachung Schleswig-Holstein', 99);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (100, 'sh_munl', 'Ministerium für Umwelt, Naturschutz und Landwirtschaft', 100);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (101, 'sh_npa', 'Nationalpark Schleswig-Holsteinisches Wattenmeer', 101);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (102, 'sh_umweltaka', 'Akademie für Natur und Umwelt des Landes Schleswig-Holstein', 102);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (103, 'sl_mfu', 'Ministerium für Umwelt', 103);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (104, 'sn_lfug', 'Sächsisches Landesamt für Umwelt und Geologie', 104);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (105, 'sn_smul', 'Staatsministerium für Umwelt und Landwirtschaft', 105);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (106, 'st_lau', 'Landesamt für Umweltschutz Sachsen-Anhalt', 106);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (107, 'st_lue', 'Luftüberwachungssystem Sachsen-Anhalt', 107);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (108, 'st_mlu', 'Ministerium für Landwirtschaft und Umwelt', 108);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (109, 'th_tlug', 'Thüringer Landesanstalt für Umwelt und Geologie', 109);
INSERT INTO `ingrid_provider` (`id`, `ident`, `name`, `sortkey`) VALUES (110, 'th_tmlnu', 'Thüringer Ministerium für Landwirtschaft, Naturschutz und Umwelt', 110);

INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (1, 'abf', 'abfall', 1);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (2, 'alt', 'altlasten', 2);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (3, 'bau', 'bauen', 3);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (4, 'bod', 'boden', 4);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (5, 'che', 'chemikalien', 5);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (6, 'ene', 'energie', 6);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (7, 'for', 'forstwirtschaft', 7);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (8, 'gen', 'gentechnik', 8);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (9, 'geo', 'geologie', 9);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (10, 'ges', 'gesundheit', 10);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (11, 'lae', 'laermerschuetterung', 11);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (12, 'lan', 'landwirtschaft', 12);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (13, 'luf', 'luftklima', 13);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (14, 'nac', 'nachhaltigeentwicklung', 14);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (15, 'nat', 'naturlandschaft', 15);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (16, 'str', 'strahlung', 16);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (17, 'tie', 'tierschutz', 17);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (18, 'uin', 'umweltinformation', 18);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (19, 'uwi', 'umweltwirtschaft', 19);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (20, 'ver', 'verkehr', 20);
INSERT INTO ingrid_env_topic (id, form_value, query_value, sortkey) VALUES (21, 'was', 'wasser', 21);

INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (1, 'rec', 'rechtliches', 1);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (2, 'kon', 'konzeptionelles', 2);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (3, 'sta', 'statusberichte', 3);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (4, 'umw', 'umweltzustand', 4);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (5, 'dat', 'datenkarten', 5);
INSERT INTO ingrid_env_funct_category (id, form_value, query_value, sortkey) VALUES (6, 'ris', 'risikobewertungen', 6);

INSERT INTO ingrid_service_rubric (id, form_value, query_value, sortkey) VALUES (1, 'pre', 'press', 1);
INSERT INTO ingrid_service_rubric (id, form_value, query_value, sortkey) VALUES (2, 'pub', 'publication', 2);
INSERT INTO ingrid_service_rubric (id, form_value, query_value, sortkey) VALUES (3, 'ver', 'event', 3);

INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (1, 'str', 'radiation', 1);
INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (2, 'luf', 'air', 2);
INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (3, 'was', 'water', 3);
INSERT INTO ingrid_measures_rubric (id, form_value, query_value, sortkey) VALUES (4, 'wei', 'misc', 4);

INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (1, 'ini', 'initiative', 1);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (2, 'his', 'historical', 2);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (3, 'law', 'law', 3);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (4, 'ins', 'institution', 4);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (5, 'dis', 'disaster', 5);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (6, 'cfe', 'conference', 6);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (7, 'cve', 'convention', 7);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (8, 'yea', 'ofTheYear', 8);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (9, 'pub', 'publication', 9);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (10, 'gui', 'guideline', 10);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (11, 'mar', 'marineAccident', 11);
INSERT INTO ingrid_chronicle_eventtypes (id, form_value, query_value, sortkey) VALUES (12, 'ind', 'industrialAccident', 12);

INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (1, 'UBA', 'RSS-UBA', 'http://www.uba.de/rss/ubapresseinfo.xml', 'de');
INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (2, 'BFN', 'BFN-UBA', 'http://www.bfn.de/6.100.html', 'de');
INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (3, 'MUF RLP', 'MUF RLP', 'http://www.muf.rlp.de/rss/rss_1_20.xml', 'de');
INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (4, 'BFN', 'BfN-Skripten', 'http://www.bfn.de/rss/skripten.xml', 'de');
INSERT INTO ingrid_rss_source (id, provider, description, url, lang) VALUES (5, 'NI_MU', 'MU_aktuell_PI_GB', 'http://www.niedersachsen.de/rss/rss_19947156_598_20.rss', 'de');


INSERT INTO PRINCIPAL_RULE_ASSOC VALUES ('admin', 'page', 'role-fallback');
INSERT INTO SECURITY_CREDENTIAL VALUES(1,1,'admin',0,'org.apache.jetspeed.security.spi.impl.DefaultPasswordCredentialImpl',0,0,1,0,0,'2004-05-22 16:27:12.572','2004-05-22 16:27:12.572',null,null,null);

INSERT INTO groups VALUES('admin');
INSERT INTO groups VALUES('manager');
INSERT INTO groups VALUES('user');
INSERT INTO roles VALUES('admin');
INSERT INTO roles VALUES('manager');
INSERT INTO roles VALUES('user');
INSERT INTO usergrouprole VALUES(1,'admin','admin','admin');
INSERT INTO usergrouprole VALUES(2,'admin','admin','manager');
INSERT INTO usergrouprole VALUES(3,'admin','admin','user');
INSERT INTO users VALUES('admin','admin');
INSERT INTO users VALUES('guest','guest');

INSERT INTO ingrid_sys_codelist VALUES (100, 'Raumbezugssystem (EPSG)', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (101, 'Vertikales Datum', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (102, 'Höhe', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (502, 'Zeitbezug des Datensatzes (Typ)', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (505, 'Adresse', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (510, 'Zeichensatz', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (515, 'Vektorformat (Geometrie)', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (517, 'Schlüsselwort', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (518, 'Periodizität', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (520, 'Medium', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (523, 'Status', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (525, 'Datensatz/Datenserie', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (526, 'Digitale Repräsentation', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (527, 'Klassifikation', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (528, 'Vektorformat (Topologie)', 1, 1);
INSERT INTO ingrid_sys_codelist VALUES (99999999, 'Sprache', 1, 0);

INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4178, 94, 'EPSG:4178 / Pulkovo 1942(83) / geographisch', 'Pulkovo 1942(83) / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4178, 121, 'EPSG:4178 / Pulkovo 1942(83) / geographisch', 'Pulkovo 1942(83) / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4230, 94, 'EPSG:4230 / ED50 / geographisch', 'ED50 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4230, 121, 'EPSG:4230 / ED50 / geographisch', 'ED50 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4258, 94, 'EPSG:4258 / ETRS89 / geographisch', 'ETRS89 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4258, 121, 'EPSG:4258 / ETRS89 / geographisch', 'ETRS89 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4284, 94, 'EPSG:4284 / Pulkovo 1942 / geographisch', 'Pulkovo 1942 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4284, 121, 'EPSG:4284 / Pulkovo 1942 / geographisch', 'Pulkovo 1942 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4314, 94, 'EPSG:4314 / DHDN / geographisch', 'DHDN / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4314, 121, 'EPSG:4314 / DHDN / geographisch', 'DHDN / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4326, 94, 'EPSG:4326 / WGS 84 / geographisch', 'WGS 84 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 4326, 121, 'EPSG:4326 / WGS 84 / geographisch', 'WGS 84 / geographisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23031, 94, 'EPSG:23031 / ED50 / UTM Zone 31N', 'ED50 / UTM Zone 31N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23031, 121, 'EPSG:23031 / ED50 / UTM Zone 31N', 'ED50 / UTM Zone 31N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23032, 94, 'EPSG:23032 / ED50 / UTM Zone 32N', 'ED50 / UTM Zone 32N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23032, 121, 'EPSG:23032 / ED50 / UTM Zone 32N', 'ED50 / UTM Zone 32N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23033, 94, 'EPSG:23033 / ED50 / UTM Zone 33N', 'ED50 / UTM Zone 33N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23033, 121, 'EPSG:23033 / ED50 / UTM Zone 33N', 'ED50 / UTM Zone 33N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23631, 94, 'EPSG:32631 / WGS 84 / UTM Zone 31N', 'WGS 84 / UTM Zone 31N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23631, 121, 'EPSG:32631 / WGS 84 / UTM Zone 31N', 'WGS 84 / UTM Zone 31N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23632, 94, 'EPSG:32632 / WGS 84 / UTM Zone 32N/33N', 'WGS 84 / UTM Zone 32N/33N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 23632, 121, 'EPSG:32632 / WGS 84 / UTM Zone 32N/33N', 'WGS 84 / UTM Zone 32N/33N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 25831, 94, 'EPSG:25831 / ETRS89 / UTM Zone 31N', 'ETRS89 / UTM Zone 31N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 25831, 121, 'EPSG:25831 / ETRS89 / UTM Zone 31N', 'ETRS89 / UTM Zone 31N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 25832, 94, 'EPSG:25832 / ETRS89 / UTM Zone 32N', 'ETRS89 / UTM Zone 32N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 25832, 121, 'EPSG:25832 / ETRS89 / UTM Zone 32N', 'ETRS89 / UTM Zone 32N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 25833, 94, 'EPSG:25833 / ETRS89 / UTM Zone 33N', 'ETRS89 / UTM Zone 33N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 25833, 121, 'EPSG:25833 / ETRS89 / UTM Zone 33N', 'ETRS89 / UTM Zone 33N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 28463, 94, 'EPSG:28463 / Pulkovo 1942 / Gauss-Krüger 2N/3N', 'Pulkovo 1942 / Gauss-Krüger 2N/3N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 28463, 121, 'EPSG:28463 / Pulkovo 1942 / Gauss-Krüger 2N/3N', 'Pulkovo 1942 / Gauss-Krüger 2N/3N', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31281, 94, 'EPSG:31281 / MGI (Ferro) / Austria West Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31281, 121, 'EPSG:31281 / MGI (Ferro) / Austria West Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31282, 94, 'EPSG:31282 / MGI (Ferro) / Austria Central Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31282, 121, 'EPSG:31282 / MGI (Ferro) / Austria Central Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31283, 94, 'EPSG:31283 / MGI (Ferro) / Austria East Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31283, 121, 'EPSG:31283 / MGI (Ferro) / Austria East Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31284, 94, 'EPSG:31284 / MGI / M28', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31284, 121, 'EPSG:31284 / MGI / M28', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31285, 94, 'EPSG:31285 / MGI / M31', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31285, 121, 'EPSG:31285 / MGI / M31', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31286, 94, 'EPSG:31286 / MGI / M34', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31286, 121, 'EPSG:31286 / MGI / M34', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31287, 94, 'EPSG:31287 / MGI / Austria Lambert', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31287, 121, 'EPSG:31287 / MGI / Austria Lambert', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31288, 94, 'EPSG:31288 / MGI (Ferro) / M28', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31288, 121, 'EPSG:31288 / MGI (Ferro) / M28', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31289, 94, 'EPSG:31289 / MGI (Ferro) / M31', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31289, 121, 'EPSG:31289 / MGI (Ferro) / M31', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31290, 94, 'EPSG:31290 / MGI (Ferro) / M34', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31290, 121, 'EPSG:31290 / MGI (Ferro) / M34', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31291, 94, 'EPSG:31291 / MGI (Ferro) / Austria West Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31291, 121, 'EPSG:31291 / MGI (Ferro) / Austria West Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31292, 94, 'EPSG:31292 / MGI (Ferro) / Austria Central Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31292, 121, 'EPSG:31292 / MGI (Ferro) / Austria Central Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31293, 94, 'EPSG:31293 / MGI (Ferro) / Austria East Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31293, 121, 'EPSG:31293 / MGI (Ferro) / Austria East Zone', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31466, 94, 'EPSG:31466 / DHDN / Gauss-Krüger Zone 2', 'DHDN / Gauss-Krüger Zone 2', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31466, 121, 'EPSG:31466 / DHDN / Gauss-Krüger Zone 2', 'DHDN / Gauss-Krüger Zone 2', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31467, 94, 'EPSG:31467 /DHDN / Gauss-Krüger Zone 3', 'DHDN / Gauss-Krüger Zone 3', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31467, 121, 'EPSG:31467 /DHDN / Gauss-Krüger Zone 3', 'DHDN / Gauss-Krüger Zone 3', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31468, 94, 'EPSG:31468 / DHDN / Gauss-Krüger Zone 4', 'DHDN / Gauss-Krüger Zone 4', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31468, 121, 'EPSG:31468 / DHDN / Gauss-Krüger Zone 4', 'DHDN / Gauss-Krüger Zone 4', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31469, 94, 'EPSG:31469 / DHDN / Gauss-Krüger Zone 5', 'DHDN / Gauss-Krüger Zone 5', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31469, 121, 'EPSG:31469 / DHDN / Gauss-Krüger Zone 5', 'DHDN / Gauss-Krüger Zone 5', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31491, 94, 'EPSG:31491 / DHDN / Germany zone 1', 'DHDN / Germany zone 1', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31491, 121, 'EPSG:31491 / DHDN / Germany zone 1', 'DHDN / Germany zone 1', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31492, 94, 'EPSG:31492 /DHDN / Germany zone 2', 'DHDN / Germany zone 2', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31492, 121, 'EPSG:31492 /DHDN / Germany zone 2', 'DHDN / Germany zone 2', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31493, 94, 'EPSG:31493 / DHDN / Germany zone 3', 'DHDN / Germany zone 3', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31493, 121, 'EPSG:31493 / DHDN / Germany zone 3', 'DHDN / Germany zone 3', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31494, 94, 'EPSG:31494 / DHDN / Germany zone 4', 'DHDN / Germany zone 4', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31494, 121, 'EPSG:31494 / DHDN / Germany zone 4', 'DHDN / Germany zone 4', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31495, 94, 'EPSG:31495 / DHDN / Germany zone 5', 'DHDN / Germany zone 5', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 31495, 121, 'EPSG:31495 / DHDN / Germany zone 5', 'DHDN / Germany zone 5', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000001, 94, 'DE_42/83 / GK_3', 'Datum 42/83 with Gauss-Krüger-System', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000001, 121, 'DE_42/83 / GK_3', 'Datum 42/83 with Gauss-Krüger-System', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000002, 94, 'DE_DHDN / GK_3', 'Datum DHDN with Gauss-Krüger-System (also known as Rauenberg or Potsdam Datum)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000002, 121, 'DE_DHDN / GK_3', 'Datum DHDN with Gauss-Krüger-System (also known as Rauenberg or Potsdam Datum)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000003, 94, 'DE_ETRS89 / UTM', 'Datum ETRS89 for Federal State Brandenburg with UTM Projection (one zone extended)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000003, 121, 'DE_ETRS89 / UTM', 'Datum ETRS89 for Federal State Brandenburg with UTM Projection (one zone extended)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000004, 94, 'DE_PD/83 / GK_3', 'Datum PD/83 with Gauss-Krüger-System (realisation of Postdam Datum for Federal State Thüringen)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000005, 121, 'DE_PD/83 / GK_3', 'Datum PD/83 with Gauss-Krüger-System (realisation of Postdam Datum for Federal State Thüringen)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000006, 94, 'DE_RD/83 / GK_3', 'Datum RD/83 with Gauss-Krüger-System (realisation of Rauenberg Datum for Federal State Sachsen)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (100, 9000006, 121, 'DE_RD/83 / GK_3', 'Datum RD/83 with Gauss-Krüger-System (realisation of Rauenberg Datum for Federal State Sachsen)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 62, 94, 'Mean Sea Level', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 62, 121, 'Mean Sea Level', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 63, 94, 'Ordnance Datum Newlyn', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 63, 121, 'Ordnance Datum Newlyn', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 64, 94, 'National Geodetic Vertical Datum 1929', '26 tide gauges in the US and Canada.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 64, 121, 'National Geodetic Vertical Datum 1929', '26 tide gauges in the US and Canada.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 65, 94, 'North American Vertical Datum 1988', 'Father''s Point, Rimouski, Quebec.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 65, 121, 'North American Vertical Datum 1988', 'Father''s Point, Rimouski, Quebec.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5105, 94, 'Baltic Sea', 'Average water level at Kronshtadt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5105, 121, 'Baltic Sea', 'Average water level at Kronshtadt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5107, 94, 'Nivellement general de la France', 'Mean sea level at Marseille', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5107, 121, 'Nivellement general de la France', 'Mean sea level at Marseille', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5109, 94, 'Normaal Amsterdams Peil', 'wird in alten Bundesländern genutzt', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5109, 121, 'Amsterdamer Pegel (NN)', 'wird in alten Bundesländern genutzt', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5110, 94, 'Oostende', 'Mean low water during 1958', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5110, 121, 'Oostende', 'Mean low water during 1958', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5113, 94, 'Sea Level', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5113, 121, 'Sea Level', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5114, 94, 'Canadian Vertical Datum of 1928', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5114, 121, 'Canadian Vertical Datum of 1928', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5115, 94, 'Piraeus Harbour 1986', 'MSL determined during 1986.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5115, 121, 'Piraeus Harbour 1986', 'MSL determined during 1986.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5116, 94, 'Helsinki 1960', 'MSL at Helsinki during 1960.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5116, 121, 'Helsinki 1960', 'MSL at Helsinki during 1960.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5117, 94, 'Rikets hojdsystem 1970', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5117, 121, 'Rikets hojdsystem 1970', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5118, 94, 'Nivellement general de la France - Lalle', 'Mean sea level at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5118, 121, 'Nivellement general de la France - Lalle', 'Mean sea level at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5119, 94, 'Nivellement general de la France - IGN69', 'Mean sea level at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5119, 121, 'Nivellement general de la France - IGN69', 'Mean sea level at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5120, 94, 'Nivellement general de la France - IGN78', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5120, 121, 'Nivellement general de la France - IGN78', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5123, 94, 'PDO Height Datum 1993', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5123, 121, 'PDO Height Datum 1993', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5127, 94, 'Landesnivellement 1902', 'Origin at Repere Pierre du Niton (RPN) 373.6 metres above msl derived at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5127, 121, 'Landesnivellement 1902', 'Origin at Repere Pierre du Niton (RPN) 373.6 metres above msl derived at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5128, 94, 'Landeshohennetz 1995', 'Origin at Repere Pierre du Niton (RPN) 373.6 metres above msl derived at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5128, 121, 'Landeshohennetz 1995', 'Origin at Repere Pierre du Niton (RPN) 373.6 metres above msl derived at Marseille.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5129, 94, 'European Vertical Reference Frame 2000', 'Geopotential number at Normaal Amsterdams Peil is zero.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5129, 121, 'European Vertical Reference Frame 2000', 'Geopotential number at Normaal Amsterdams Peil is zero.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5130, 94, 'Malin Head', 'Mean sea level between January 1960 and December 1969.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5130, 121, 'Malin Head', 'Mean sea level between January 1960 and December 1969.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5131, 94, 'Belfast Lough', 'Mean sea level between 1951 and 1956 at Clarendon Dock, Belfast.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5131, 121, 'Belfast Lough', 'Mean sea level between 1951 and 1956 at Clarendon Dock, Belfast.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5132, 94, 'Dansk Normal Nul', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5132, 121, 'Dansk Normal Nul', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5138, 94, 'Ordnance Datum Newlyn (Orkney Isles)', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5138, 121, 'Ordnance Datum Newlyn (Orkney Isles)', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5139, 94, 'Fair Isle', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5139, 121, 'Fair Isle', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5140, 94, 'Lerwick', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5140, 121, 'Lerwick', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5141, 94, 'Foula', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5141, 121, 'Foula', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5142, 94, 'Sule Skerry', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5142, 121, 'Sule Skerry', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5143, 94, 'North Rona', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5143, 121, 'North Rona', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5144, 94, 'Stornoway', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5144, 121, 'Stornoway', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5145, 94, 'St. Kilda', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5145, 121, 'St. Kilda', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5146, 94, 'Flannan Isles', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5146, 121, 'Flannan Isles', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5147, 94, 'St. Marys', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5147, 121, 'St. Marys', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5148, 94, 'Douglas', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5148, 121, 'Douglas', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5149, 94, 'Fao', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5149, 121, 'Fao', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5151, 94, 'Nivellement General Nouvelle Caledonie', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 5151, 121, 'Nivellement General Nouvelle Caledonie', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900001, 94, 'Kronstädter Pegel (HN)', 'wird in neuen Bundesländern genutzt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900001, 121, 'Kronstädter Pegel (HN)', 'wird in neuen Bundesländern genutzt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900002, 94, 'DE_AMST / NH', 'normal heights referred to tide gauge Amsterdam (also known as DHHN92)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900002, 121, 'DE_AMST / NH', 'normal heights referred to tide gauge Amsterdam (also known as DHHN92)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900003, 94, 'DE_AMST / NOH', 'normal-orthometric heights referred to tide gauge Amsterdam (also known as DHHN85)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900003, 121, 'DE_AMST / NOH', 'normal-orthometric heights referred to tide gauge Amsterdam (also known as DHHN85)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900004, 94, 'DE_KRON / NH', 'normal heights referred to tide gauge Kronstadt (also known as SNN76)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (101, 900004, 121, 'DE_KRON / NH', 'normal heights referred to tide gauge Kronstadt (also known as SNN76)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 4, 94, 'Zoll', 'Zoll', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 4, 121, 'Inch', 'Inch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 9001, 94, 'Metre', 'Metre', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 9001, 121, 'Meter', 'Meter', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 9002, 94, 'Foot', 'Foot', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 9002, 121, 'Fuss', 'Fuss', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 9036, 94, 'Kilometre', 'Kilometre', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (102, 9036, 121, 'Kilometer', 'Kilometer', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (502, 1, 94, 'creation', 'date identifies when the resource was brought into existence', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (502, 1, 121, 'Erstellung', 'Datum, wann die Quelle geschaffen wurde', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (502, 2, 94, 'publication', 'date identifies when the resource was issued', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (502, 2, 121, 'Publikation', 'Dateum, wann die Quelle publiziert wurde', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (502, 3, 94, 'revision', 'date identifies when the resource was examined or re-examined and improved or amended', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (502, 3, 121, 'letzte Änderung', 'Datum, wann eine Revision durchgeführt wurde', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 1, 94, 'Provider', 'Party that supplies the resource', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 1, 121, 'Anbieter', 'Anbieter der Datenquelle', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 2, 94, 'Custodian', 'Party that accepts accountability and responsibility for the data and ensures appropriate care and maintenance of the resource', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 2, 121, 'Datenverantwortung', 'Verantworlicher für die Datenquelle und deren Pflege', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 3, 94, 'Owner', 'Party that owns the resource', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 3, 121, 'Halter', 'Halter der Datenquelle', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 4, 94, 'User', 'Party who uses the resource', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 4, 121, 'Benutzer', 'Benutzer der Datenquelle', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 5, 94, 'Distributor', 'Party who distributes the resource', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 5, 121, 'Vertrieb', 'Vertreiber der Datenquelle', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 6, 94, 'Originator', 'Party who created the resource', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 6, 121, 'Herkunft', 'Ersteller der Datenquelle', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 7, 94, 'Point of Contact', 'Party who can be contacted for acquiring knowledge about or acquisition of the resource', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 7, 121, 'Auskunft', 'Kontaktperson, die Informationen über die Datenqulle geben kann', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 8, 94, 'Principal Investigator', 'Key party responsible for gathering information and conducting research', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 8, 121, 'Datenerfassung', 'Verantworlicher für die Zusammenstellung der Informationen und Durchführung von Forschung', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 9, 94, 'Processor', 'Party who has processed the data in a manner such that the resource has been modified', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 9, 121, 'Auswertung', 'Bearbeiter der Daten in einer Art, dass die Quelle modifiziert wurde.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 10, 94, 'Publisher', 'Party who published the resource', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (505, 10, 121, 'Herausgeber', 'Phblizierer der Datenquelle', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 1, 94, 'ucs2', '16-bit fixed size Universal Character Set, based on ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 1, 121, 'ucs2', '16-bit fixierte Größe Universal Character Set, basierend auf ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 2, 94, 'ucs4', '32-bit fixed size Universal Character Set, based on ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 2, 121, 'ucs4', '32-bit fixierte Größe Universal Character Set, basierend auf ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 3, 94, 'utf7', '7-bit variable size UCS Transfer Format, based on ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 3, 121, 'utf7', '7-bit variable Größe UCS Transfer Format, basierend auf ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 4, 94, 'utf8', '8-bit variable size UCS Transfer Format, based on ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 4, 121, 'utf8', '8-bit variable Größe UCS Transfer Format, basierend auf ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 5, 94, 'utf16', '16-bit variable size UCS Transfer Format, based on ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 5, 121, 'utf16', '16-bit variable Größe UCS Transfer Format, basierend auf ISO/IEC 10646', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 6, 94, '8859part1', 'latin-1, west European', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 6, 121, '8859part1', 'latin-1, Westeuropäischer', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 7, 94, '8859part2', 'latin-2, central European', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 7, 121, '8859part2', 'latin-2, Zentraleuropäischer', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 8, 94, '8859part3', 'latin-3, south European', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 8, 121, '8859part3', 'latin-3, Südeuropäischer', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 9, 94, '8859part4', 'latin-4, north European', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 9, 121, '8859part4', 'latin-4, Nordeuropäischer', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 10, 94, '8859part5', 'cyrillic code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 10, 121, '8859part5', 'Cyrillisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 11, 94, '8859part6', 'arabic code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 11, 121, '8859part6', 'Arabisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 12, 94, '8859part7', 'greek code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 12, 121, '8859part7', 'Griechisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 13, 94, '8859part8', 'hebrew code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 13, 121, '8859part8', 'Hebräisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 14, 94, '8859part9', 'latin-5, Turkish code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 14, 121, '8859part9', 'latin-5, Türkisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 15, 94, '8859part11', 'thai code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 15, 121, '8859part11', 'Tailändisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 16, 94, '8859part14', 'latin-8 code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 16, 121, '8859part14', 'latin-8', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 17, 94, '8859part15', 'latin-9 code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 17, 121, '8859part15', 'latin-9', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 18, 94, 'Jis', 'japanese code set used for electronic transmission', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 18, 121, 'Jis', 'Japanisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 19, 94, 'ShiftJIS', 'japanese code set used on MS-DOS based machines', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 19, 121, 'ShiftJIS', 'Japanisch (MS-DOS)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 20, 94, 'EucJP', 'japanese code set used on UNIX based machines', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 20, 121, 'EucJP', 'Japanisch (UNIX)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 21, 94, 'UsAscii', 'united states ASCII code set (ISO 646 US)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 21, 121, 'UsAscii', 'USA ASCII', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 22, 94, 'Ebcdic', 'ibm mainframe code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 22, 121, 'Ebcdic', 'IBM Mainfraime', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 23, 94, 'EucKR', 'korean code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 23, 121, 'EucKR', 'Koreanisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 24, 94, 'big5', 'taiwanese code set', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (510, 24, 121, 'big5', 'Tawainesisch', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 1, 94, 'complexes', 'set of geometric primitives such that their boundaries can be represented as a union of other primitives', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 1, 121, 'Komplex', 'Satz geometrischer Primitiver, wobei deren Grenzen durch ein Zusammenschluss anderer Primitiver gebildet werden können', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 2, 94, 'composites', 'connected set of curves, solids or surfaces', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 2, 121, 'Verbund', 'verbundener Satz von Kurven, Körpern oder Oberflächen', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 3, 94, 'curve', 'bounded, 1-dimensional geometric primitive, representing the continuous image of a line', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 3, 121, 'Kurve', 'beschränkte, 1-D geometrische Primitive, die ein continuierliches Bild einer Linie darstellt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 4, 94, 'point', 'zero-dimensional geometric primitive, representing a position but not having an extent', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 4, 121, 'Punkt', '0-D geometrische Primitive, welche eine Position beschreibt ohne eine Ausdehnung zu haben', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 5, 94, 'solid', 'bounded, connected 3-dimensional geometric primitive, representing the continuous image of a region of space', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 5, 121, 'Körper', 'begrenzte, verbundene 3-D geometrische Primitive, welche ein kontinuierliches Bild eines Raumes beschreibt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 6, 94, 'surface', 'bounded, connected 2-dimensional geometric, representing the continuous image of a region of a plane', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (515, 6, 121, 'Oberfläche', 'begrenzte, verbundene 2-D geometrische Primitive, welche ein kontinuierliches Bild einer Ebene oder Region beschreibt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 1, 94, 'Discipline', 'keyword identifies a branch of instruction or specialized learning', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 1, 121, 'Wissenszweig', 'Zweig einer Ausbildung oder spezialisierten Lernens', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 2, 94, 'Place', 'keyword identifies a location', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 2, 121, 'Ortsangabe', 'Ortsangabe', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 3, 94, 'Stratum', 'keyword identifies the layer(s) of any deposited substance', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 3, 121, 'Schicht', 'Schichten einer hinterlegten Substanz', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 4, 94, 'Temporal', 'keyword identifies a time period related to the dataset', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 4, 121, 'Zeitraum', 'Zeitraum in Bezug auf den Datensatz', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 5, 94, 'Theme', 'keyword identifies a particular subject or topic', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (517, 5, 121, 'Themenbereich', 'Spezielles Fachgebiet oder Thema', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 1, 94, 'continual', 'data is repeatedly and frequently updated', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 1, 121, 'kontinuierlich', 'Datenupdate  häufig', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 2, 94, 'daily', 'Data is updated each day', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 2, 121, 'täglich', 'Datenupdate täglich', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 3, 94, 'weekly', 'Ddata is updated on a weekly basis', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 3, 121, 'wöchentlich', 'Datenupdate wöchentlich', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 4, 94, 'fortnightly', 'Data is updated every two weeks', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 4, 121, 'vierzehntägig', 'Datenupdate alle 2 Wochen', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 5, 94, 'monthly', 'Data is updated each month', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 5, 121, 'monatlich', 'Datenupdate monatlich', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 6, 94, 'quarterly', 'Data is updated every three months', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 6, 121, 'vierteljährlich', 'Datenupdate alle 3 Monate', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 7, 94, 'biannually', 'Data is updated twice each year', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 7, 121, 'halbjährlich', 'Datenupdate halbjährlich', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 8, 94, 'annually', 'Data is updated every year', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 8, 121, 'jährlich', 'Datenupdate jährlich', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 9, 94, 'as Needed', 'Data is updated as deemed necessary', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 9, 121, 'bei Bedarf', 'Datenupdate wenn nötig', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 10, 94, 'irregular', 'Data is updated in intervals that are uneven in duration', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 10, 121, 'unregelmäßig', 'Datenupdate in unregelmäßigen Abständen', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 11, 94, 'notPlanned', 'There are no plans to update the data', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 11, 121, 'einmalig', 'Datenupdate nicht geplant', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 12, 94, 'unknown', 'Frequency of maintenance for the data is not known', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (518, 12, 121, 'unbekannt', 'Datenupdate unbekannt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 1, 94, 'CD Rom', 'CD Rom', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 1, 121, 'CD-ROM', 'CD-ROM', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 2, 94, 'dvd', 'dvd', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 2, 121, 'DVD', 'DVD', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 3, 94, 'dvd Rom', 'dvd Rom', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 3, 121, 'DVD-ROM', 'DVD-ROM', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 4, 94, '3.5-inch diskette', '3'''' Floppy', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 4, 121, '3,5-Zoll Diskette', '3Â¿Â¿ Floppy', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 5, 94, '5.25-inch diskette', '5 Â¼Â¿Â¿ Floppy', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 5, 121, '5,25-Zoll Diskette', '5 Â¼Â¿Â¿ Floppy', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 6, 94, '7 trackTape', '7 trackTape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 6, 121, '7 Spur Band', '7 Spur Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 7, 94, '9 track Tape', '9 track Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 7, 121, '9 Spur Band', '9 Spur Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 8, 94, '3480 Cartridge', '3480Cartridge', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 8, 121, '3480 Bandkassette', '3480 Cartridge', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 9, 94, '3490 Cartridge', '3490 Cartridge', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 9, 121, '3490 Bandkassette', '3490 Cartridge', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 10, 94, '3580 Cartridge', '3580Cartridge', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 10, 121, '3580 Bandkassette', '3580 Cartridge', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 11, 94, '4mm Cartridge Tape', '4mm Cartridge Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 11, 121, '4mm Bandkassette', '4mm Cartridge Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 12, 94, '8mm Cartridge Tape', '8mm Cartridge Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 12, 121, '8mm Bandkassette', '8mm Cartridge Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 13, 94, '0.25-inch Cartridge Tape', 'Â¼ `Â¿ Cartridge Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 13, 121, '1/4-Zoll Bandkassette', 'Â¼ `Â¿ Cartridge Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 14, 94, 'Digital Linear Tape', 'digital Linear Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 14, 121, 'Digitales Band', 'Digitales Tape', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 15, 94, 'Online', 'online', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 15, 121, 'Online Link', 'Online Link', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 16, 94, 'Satellite', 'Satellite', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 16, 121, 'Satellitenverbindung', 'Satellitenverbindung', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 17, 94, 'Telephone Link', 'telephone Link', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 17, 121, 'Telefon', 'Telefonverbindung', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 18, 94, 'Hardcopy', 'hardcopy', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 18, 121, 'Papier', 'Kopie (Papier), Druckerzeugnisse usw.', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900001, 94, 'unknown', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900001, 121, 'unbekannt (*)', 'für Altdatenübernahme', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900002, 94, 'faxback', 'faxback', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900002, 121, 'Faxabruf', 'Faxabruf', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900003, 94, 'mobile radio', 'mobile radio', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900003, 121, 'Mobilfunk', 'Mobilfunk', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900004, 94, 'broadcast', 'broadcast', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900004, 121, 'Rundfunk', 'Rundfunk und Fernsehen', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900005, 94, 'video text', 'video text', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900005, 121, 'Videotext', 'Videotext', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900006, 94, 'Analog Photography', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900006, 121, 'analoge Fotografie', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900007, 94, 'microfilm', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900007, 121, 'Mikrofilm', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900008, 94, 'Zip Drive', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900008, 121, 'ZIP-Laufwerk', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900009, 94, 'e-mail', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900009, 121, 'E-Mail', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900010, 94, 'Info Kiosk', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (520, 900010, 121, 'Infokiosk', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 1, 94, 'completed', 'production of the data has been completed', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 1, 121, 'abgeschlossen', 'Datenproduktion ist abgeschlossen', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 2, 94, 'historicalArchive', 'Data has been stored in an offline storage facility', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 2, 121, 'archiviert', 'Die Daten sind in einem Archiv abgelegt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 3, 94, 'obsolete', 'Data is no longer relevant', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 3, 121, 'obsolet', 'Die Daten sind nicht mehr länger relevant', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 4, 94, 'onGoing', 'Data is continually being updated', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 4, 121, 'kontinuierlich', 'Daten werden kontinuierlich erneuert', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 5, 94, 'planned', 'fixed date has been established upon or by which the data will be created or updated', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 5, 121, 'geplant', 'Ein Zeitpunkt wurde festgelegt, an dem die Daten kreiert werden', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 6, 94, 'required', 'Data needs to be generated or updated', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 6, 121, 'benötigt', 'Die Daten müssen generiert bzw. erneuert werden', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 7, 94, 'underdevelopment', 'Data is currently in the process of being created', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 7, 121, 'in Erstellung', 'Die Daten werden gerade kreiert', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 900001, 94, 'inOperation', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (523, 900001, 121, 'in Produktion', 'Informationssystem als produktiv genutztes System', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (525, 5, 94, 'Dataset', 'information applies to the dataset', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (525, 5, 121, 'Datensatz', 'Information zu dem Datensatz', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (525, 6, 94, 'Dataseries', 'information applies to the series', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (525, 6, 121, 'Datenserie', 'Information zu der Datenserie', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 1, 94, 'vector', 'vector data is used to represent geographic data', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 1, 121, 'Vektor', 'Geographische Daten werden mittels Verktordaten präsentiert', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 2, 94, 'grid', 'grid data is used to represent geographic data', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 2, 121, 'Rasterdaten', 'Geographische Daten werden mittels Rasterdaten dargestellt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 3, 94, 'textTable', 'textual or tabular data is used to represent geographic data', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 3, 121, 'Texttabelle', 'Geographische Daten werden mittels Texttabellen dargestellt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 4, 94, 'TIN', 'triangulated irregular network', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 4, 121, 'TIN', 'Geographische Daten werden mittels eines trinangulären irregulären Netzes dargestellt dargestellt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 5, 94, 'stereoModel', 'three-dimensional view formed by the intersecting homologous rays of an overlapping pair of images', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 5, 121, 'Stereomodell', 'Geographische Daten werden mittels eines stereosehenden Models dargestellt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 6, 94, 'video', 'scene from a video recording', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (526, 6, 121, 'Video', 'Geographische Daten werden mittels einer Videoaufnahme dargestellt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 1, 94, 'Farming', 'rearing of animals and/or cultivation of plants', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 1, 121, 'Landwirtschaft', 'Landwirtschaft (Tierzucht oder Pflanzenanbau)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 2, 94, 'Biota', 'flora and/or fauna in natural environment. Examples: wildlife, vegetation, biological sciences, ecology, wilderness, sealife, wetlands, habitat', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 2, 121, 'Flora, Fauna, Habitate', 'Flora und Fauna in der natürlichen Umwelt', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 3, 94, 'Boundaries', 'legal land descriptions. Examples: political and administrative boundaries', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 3, 121, 'Grenzen', 'Rechtl. Beschreibungen und Grenzen von Land', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 4, 94, 'Climatology MeteorologyAtmosphere', 'processes and phenomena of the atmosphere. Examples: cloud cover, weather, climate, atmospheric conditions, climate change, precipitation', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 4, 121, 'Klima und Atmosphäre', 'Prozesse und Phänomene der Atmosphäre', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 5, 94, 'Economy', 'economic activities, conditions and employment. Examples: production, labour, revenue, commerce, industry, tourism and ecotourism, forestry, fisheries, commercial or subsistence hunting, etc.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 5, 121, 'Ökonomie', 'Ökonomische Aktivitäten, Konditionen und beschäftigung', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 6, 94, 'Elevation', 'height above or below sea level. Examples: altitude, bathymetry, digital elevation models, slope, derived products', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 6, 121, 'Höhe', 'Höhe über oder unter NN', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 7, 94, 'Environment', 'environmental resources, protection and conservation. Examples: environmental pollution, waste storage and treatment, environmental impact assessment, monitoring environmental risk, nature reserves, landscape', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 7, 121, 'Umwelt', 'Umweltresourcen, -schutz und -erhaltung', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 8, 94, 'Geoscientific Information', 'information pertaining to earth sciences. Examples: geophysical features and processes, geology, minerals, sciences dealing with the composition, structure and origin of the earthÂ¿s rocks, risks of earthquakes', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 8, 121, 'Geowissenschaft', 'Information die Geowissenshaften betreffend', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 9, 94, 'Health', 'health, health services, human ecology, and safety. Examples: disease and illness, factors affecting health, hygiene, substance abuse, mental and physical health, health services', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 9, 121, 'Gesundheit', 'Gesundheit, Gesundheitsservices, Humanökologie und Sicherheit', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 10, 94, 'Imagery Base Maps EarthCover', 'base maps. Examples: land cover, topographic maps, imagery, unclassified images, annotations', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 10, 121, 'Karten', 'Karten', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 11, 94, 'Intelligence Military', 'military bases, structures, activities. Examples: barracks, training grounds, military transportation, information', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 11, 121, 'Militär', 'Militärische Stützpunkte, Strikturen und Aktivitäten', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 12, 94, 'Inland Waters', 'inland water features, drainage systems and their characteristics. Examples: rivers and glaciers, salt lakes, water utilization plans, dams, currents, floods, water quality, hydrographic charts', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 12, 121, 'Binnengewässer', 'Inlandwasser, Abflüsse und deren Eigenschaften und Charakteristika', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 13, 94, 'Location', 'positional information and services. Examples: addresses, geodetic networks, control points, postal zones and services, place names', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 13, 121, 'Ortsangabe', 'Ortsangaben und -services', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 14, 94, 'Oceans', 'features and characteristics of salt water bodies (excluding inland waters): Examples: tides, tidal waves, coastal information, reefs', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 14, 121, 'Ozeane', 'Ozeane und deren Charakteristika und Eigenschaften', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 15, 94, 'PlanningCadastre', 'information used for appropriate actions for future use of the land Examples: land use maps, zoning maps, cadastral surveys, land ownership', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 15, 121, 'Kataster', 'Informationen zu angemessenem Handeln für die zukünftige Nutzung des Landes', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 16, 94, 'Society', 'characteristics of society and cultures. Examples: settlements, anthropology, archaeology, education, traditionalbeliefs, manners and customs, demographic data, recreational areas and activities,', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 16, 121, 'Gesellschaft', 'Charakteristika von Gesellschaft und Kulturen', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 17, 94, 'Structure', 'man-made construction. Examples: buildings, museums, churches, factories, housing, monuments, shops, towers', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 17, 121, 'Bau', 'Kontsruktionen (von Menschen geshaffen)', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 18, 94, 'Transportation', 'means and aids for conveying persons and/or goods. Examples: roads, airports/airstrips, shipping routes, tunnels, nautical charts, vehicle or vessel location, aeronautical charts, railways', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 18, 121, 'Transport', 'Hilfsmittel und Geräte zum Befördern von Personen und/oder Gütern', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 19, 94, 'Utilities Communication', 'energy, water and waste systems and communications infrastructure and services. Examples: hydroelectricity, geothermal, solar and nuclear sources of energy, water purification and distribution, sewage collection and disposal, etc.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (527, 19, 121, 'Energie und Kommunikation', 'Energie-, Wasser- und Abfallsysteme sowie Kommunikationsinfrastruktur und Services.', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 1, 94, 'geometryOnly', 'geometry objects without any additional structure which describes topology', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 1, 121, 'geometrisch', 'Geometrisch Objekte ohn jegliche Struktur, die die Topologie beschreibt', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 2, 94, 'topology1D', '1-dimensional topological complex', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 2, 121, 'Topologie (1D)', '1-dimensionaler topologischer Komplex', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 3, 94, 'planarGraph', '1-dimensional topological complex which is planar', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 3, 121, 'Planar (1D)', '1-dimensionaler topologischer Komplex, der eine Fläche ist', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 4, 94, 'fullPlanarGraph', '2-dimensional topological complex which is planar', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 4, 121, 'Planar (2D)', '2-dimensionaler topologischer Komplex, der eine Fläche ist', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 5, 94, 'surfaceGraph', '1-dimensional topological complex which is isomorphic to a subset of a surface', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 5, 121, 'Oberflächengraph (1D)', '1-dimensionaler topologischer Komplex, der isomorph zu einer Untermenge einer Oberfläche ist', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 6, 94, 'fullSurfaceGraph', '2-dimensional topological complex which is isomorphic to a subset of a surface', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 6, 121, 'Oberfläche(2D)', '2-dimensionaler topologischer Komplex, der isomorph zu einer Untermenge einer Oberfläche ist', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 7, 94, 'topology3D', '3-dimensional topological complex', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 7, 121, 'Topologie (3D)', '3-dimensionaler topologischer Komplex', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 8, 94, 'fullTopology3D', 'complete coverage of a 3D coordinate space', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 8, 121, 'Raum (3D)', 'Komplette Abdeckung eines 3-D Koordinatenraumes', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 9, 94, 'abstract', 'topological complex without any specified geometric realization', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (528, 9, 121, 'Abstrakte Topologie', 'Topologischer Komplex ohne jegliche spezifische geometrische Realisierung', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (99999999, 94, 94, 'English', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (99999999, 94, 121, 'Englisch', '-', 0);
INSERT INTO ingrid_sys_codelist_domain VALUES (99999999, 121, 94, 'German', '-', 1);
INSERT INTO ingrid_sys_codelist_domain VALUES (99999999, 121, 121, 'Deutsch', '-', 1);

