# allowed DPIs
dpis: [150]

#
# the list of allowed hosts
#
hosts:
  # allow all
  - !acceptAll {}

#
# allowed scales
#
scales:
  - 500
  - 1000
  - 2000
  - 2500
  - 5000
  - 10000
  - 15000
  - 20000
  - 25000
  - 50000
  - 100000
  - 200000
  - 500000
  - 1000000
  - 2000000
  - 4000000

globalParallelFetches: 32
perHostParallelFetches: 32
connectionTimeout: 30000
socketTimeout: 60000

ignoreCapabilities: true
maxPrintTimeBeforeWarningInSeconds: 120
printTimeoutMinutes: 5

#---------------------------------------
# A4 portrait:
#---------------------------------------
layouts:
  1 A4 Hochformat:
    mainPage:
      pageSize: A4
      rotation: true

      items:

#---------------------------------------
# Title / Description
#---------------------------------------
        - !columns
          condition: title
          absoluteX: 150
          absoluteY: 820
          width: 300
          nbColumns: 1
          config:
            cells:
              - padding: 5
              - backgroundColor: white
              - align: center
          items:
            - !text
              fontSize: 16
              text: |
                ${title}
            - !text
              condition: comment
              fontSize: 10
              text: |
                ${comment}

#---------------------------------------
# Logo
#---------------------------------------
        - !columns
          absoluteX: 10
          absoluteY: 835
          width: 70
          items:
              - !image
                   align: left
                   maxWidth: 70
                   url: "${logo}"

        - !columns
          absoluteX: 80
          absoluteY: 830
          width: 100
          items:
              - !text
                   fontColor: '#007A89'
                   fontSize: 13
                   align: left
                   text: |
                     GeoPortal.WSV

#---------------------------------------
# Map
#---------------------------------------
        - !map
          absoluteX: 20
          absoluteY: 765
          width: 550
          height: 695

#---------------------------------------
# Copyright
#---------------------------------------
        - !columns
          absoluteY: 64
          absoluteX: 25
          width: 300
          items:
            - !text
              fontSize: 7
              align: left
              text: |
                ${dataOwner}

#-------------------------------------
# Scalesbar
#-------------------------------------
        - !columns
          absoluteY: 64
          absoluteX: 442
          width: 128
          config:
            borderWidth: 0.5
          items:
              - !text
                fontSize: 43
                text: ' '
                backgroundColor: white
        - !columns
          absoluteY: 59
          absoluteX: 445
          width: 124
          nbColumns: 1
          items:
            - !scalebar
                type: line
                units: m
                color: black
                align: center
                fontSize: 8
                maxSize: 128
            - !text
              condition: langde
              fontSize: 7
              align: center
              text: |
                Massstab 1: ${format %,d scale}
                Gedruckt am ${now dd.MM.yyyy HH:mm}
                ${shortLink}
            - !text
              condition: langen
              fontSize: 7
              align: center
              text: |
                Scale 1: ${format %,d scale}
                Printed on ${now dd.MM.yyyy HH:mm}
                ${shortLink}
#---------------------------------------
# North arrow
#---------------------------------------
        - !columns
          absoluteY: 60
          absoluteX: 405
          width: 30
          items:
            - !image
              rotation: '${rotation}'
              maxWidth: 30
              maxHeight: 30
              url: "${northArrow}"

    lastPage:
      landscape: false
      items:

##---------------------------------------
## Legend title
##---------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 820
          width: 551
          condition: "enableLegends"
          items:
            - !text
              fontSize: 12
              align: center
              text: |
                ${legendTitle}

##---------------------------------------
## Legend
##---------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 800
          width: 551
          condition: "enableLegends"
          items:
            - !legends
              horizontalAlignment: left
              maxWidth: 0
              maxHeight: 420
              iconMaxWidth: 250
              iconMaxHeight: 420
              defaultScale: 0.75
              classIndentation: 3
              layerSpace: 5
              classSpace: 5
              layerFontSize: 9
              columnMargin: 5
              backgroundColor: white
              inline: false

#---------------------------------------
# A4 landscape:
#---------------------------------------
  2 A4 Querformat:
    mainPage:
      rotation: true
      pageSize: A4
      landscape: true
      items:

#---------------------------------------
# Title / Description
#---------------------------------------
        - !columns
          condition: title
          absoluteX: 255
          absoluteY: 575
          width: 300
          nbColumns: 1
          config:
            cells:
              - padding: 5
              - backgroundColor: white
              - align: center
          items:
            - !text
              fontSize: 16
              text: |
                ${title}
            - !text
              condition: comment
              fontSize: 10
              text: |
                ${comment}

#---------------------------------------
# Logo
#---------------------------------------
        - !columns
          absoluteX: 10
          absoluteY: 585
          width: 80
          items:
              - !image
                   align: left
                   maxWidth: 80
                   url: "${logo}"

        - !columns
          absoluteX: 90
          absoluteY: 580
          width: 100
          items:
              - !text
                   fontColor: '#007A89'
                   fontSize: 13
                   align: left
                   text: |
                     GeoPortal.WSV

#---------------------------------------
# Map
#---------------------------------------
        - !map
          absoluteX: 20
          absoluteY: 515
          width: 802
          height: 450

#---------------------------------------
# North arrow
#---------------------------------------
        - !columns
          absoluteY: 55
          absoluteX: 540
          width: 150
          items:
            - !image
              rotation: '${rotation}'
              align: right
              maxWidth: 30
              maxHeight: 30
              url: "${northArrow}"

#---------------------------------------
# Copyright
#---------------------------------------
        - !columns
          absoluteY: 60
          absoluteX: 25
          width: 300
          items:
            - !text
              fontSize: 7
              align: left
              text: |
                ${dataOwner}

#-------------------------------------
# Scalesbar
#-------------------------------------
        - !columns
          absoluteY: 60
          absoluteX: 695
          width: 128
          config:
            borderWidth: 0.5
          items:
              - !text
                fontSize: 43
                text: ' '
                backgroundColor: white
        - !columns
          absoluteY: 55
          absoluteX: 698
          width: 124
          nbColumns: 1
          items:
            - !scalebar
                type: line
                units: m
                color: black
                align: center
                vertAlign: top
                fontSize: 8
                maxSize: 128
            - !text
              condition: langde
              fontSize: 7
              align: center
              text: |
                Massstab 1: ${format %,d scale}
                Gedruckt am ${now dd.MM.yyyy HH:mm}
                ${shortLink}
            - !text
              condition: langen
              fontSize: 7
              align: center
              text: |
                Scale 1: ${format %,d scale}
                Printed on ${now dd.MM.yyyy HH:mm}
                ${shortLink}

    lastPage:
      landscape: true
      items:

##---------------------------------------
## Legend title
##---------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 575
          width: 798
          condition: "enableLegends"
          items:
            - !text
              fontSize: 12
              align: center
              text: |
                ${legendTitle}

##--------------------------------------
## Legend
##--------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 555
          width: 798
          condition: "enableLegends"
          items:
            - !legends
              horizontalAlignment: left
              maxHeight: 420
              maxWidth: 0
              iconMaxWidth: 200
              iconMaxHeight: 420
              defaultScale: 0.75
              classIndentation: 3
              layerSpace: 5
              classSpace: 5
              layerFontSize: 9
              inline: false
              columnMargin: 5
              backgroundColor: white

#---------------------------------------
# A3 portrait:
#---------------------------------------
  3 A3 Hochformat:
    mainPage:
      pageSize: A3
      rotation: true

      items:

#---------------------------------------
# Title / Description
#---------------------------------------
        - !columns
          condition: title
          absoluteX: 0
          absoluteY: 1170
          width: 842
          nbColumns: 1
          config:
            cells:
              - paddingLeft: 175
              - paddingRight: 175
              - paddingBottom: 10
          items:
            - !text
              fontSize: 16
              align: center
              text: |
                ${title}
            - !text
              condition: comment
              fontSize: 10
              align: center
              text: |
                ${comment}

#---------------------------------------
# Logo
#---------------------------------------
        - !columns
          absoluteX: 10
          absoluteY: 1180
          width: 80
          items:
              - !image
                   align: left
                   maxWidth: 80
                   url: "${logo}"

        - !columns
          absoluteX: 85
          absoluteY: 1170
          width: 130
          items:
              - !text
                   fontColor: '#007A89'
                   fontSize: 15
                   align: left
                   text: |
                     GeoPortal.WSV

#---------------------------------------
# Map
#---------------------------------------
        - !map
          absoluteX: 20
          absoluteY: 1105
          width: 802
          height: 1035

#---------------------------------------
# Copyright
#---------------------------------------
        - !columns
          absoluteY: 65
          absoluteX: 20
          width: 405
          items:
            - !text
              fontSize: 8
              align: left
              text: |
                ${dataOwner}

#-------------------------------------
# Scalesbar
#-------------------------------------
        - !columns
          absoluteY: 65
          absoluteX: 695
          width: 128
          config:
            borderWidth: 0.5
          items:
              - !text
                fontSize: 43
                text: ' '
                backgroundColor: white
        - !columns
          absoluteY: 61
          absoluteX: 698
          width: 124
          nbColumns: 1
          items:
            - !scalebar
                type: line
                units: m
                color: black
                align: center
                fontSize: 8
                maxSize: 128
            - !text
              condition: langde
              fontSize: 7
              align: center
              text: |
                Massstab 1: ${format %,d scale}
                Gedruckt am ${now dd.MM.yyyy HH:mm}
                ${shortLink}
            - !text
              condition: langen
              fontSize: 7
              align: center
              text: |
                Scale 1: ${format %,d scale}
                Printed on ${now dd.MM.yyyy HH:mm}
                ${shortLink}

#---------------------------------------
# North arrow
#---------------------------------------
        - !columns
          absoluteY: 60
          absoluteX: 655
          width: 30
          items:
            - !image
              rotation: '${rotation}'
              maxWidth: 30
              maxHeight: 30
              url: "${northArrow}"

    lastPage:
      landscape: false
      items:

##---------------------------------------
## Legend title
##---------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 820
          width: 551
          condition: "enableLegends"
          items:
            - !text
              fontSize: 12
              align: center
              text: |
                ${legendTitle}

##---------------------------------------
## Legend
##---------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 800
          width: 551
          condition: "enableLegends"
          items:
            - !legends
              horizontalAlignment: left
              maxHeight: 420
              maxWidth: 0
              iconMaxWidth: 250
              iconMaxHeight: 420
              defaultScale: 0.75
              classIndentation: 3
              layerSpace: 5
              classSpace: 5
              layerFontSize: 9
              columnMargin: 5
              backgroundColor: white
              inline: false

#---------------------------------------
# A3 landscape:
#---------------------------------------
  4 A3 Querformat:
    mainPage:
      rotation: true
      pageSize: A3
      landscape: true
      items:

#---------------------------------------
# Title / Description
#---------------------------------------
        - !columns
          condition: title
          absoluteX: 225
          absoluteY: 822
          width: 800
          nbColumns: 1
          config:
            cells:
              - paddingLeft: 175
              - paddingRight: 175
              - paddingBottom: 10
          items:
            - !text
              fontSize: 16
              align: center
              text: |
                ${title}
            - !text
              condition: comment
              fontSize: 10
              align: center
              text: |
                ${comment}

#---------------------------------------
# Logo
#---------------------------------------
        - !columns
          absoluteX: 10
          absoluteY: 830
          width: 80
          items:
              - !image
                   align: left
                   maxWidth: 80
                   url: "${logo}"

        - !columns
          absoluteX: 85
          absoluteY: 820
          width: 130
          items:
              - !text
                   fontColor: '#007A89'
                   fontSize: 15
                   align: left
                   text: |
                     GeoPortal.WSV

#---------------------------------------
# Map
#---------------------------------------
        - !map
          absoluteX: 20
          absoluteY: 752
          width: 1150
          height: 675

#---------------------------------------
# Copyright
#---------------------------------------
        - !columns
          absoluteY: 70
          absoluteX: 25
          width: 300
          items:
            - !text
              fontSize: 7
              align: left
              text: |
                ${dataOwner}

#-------------------------------------
# Scalesbar
#-------------------------------------
        - !columns
          absoluteY: 65
          absoluteX: 1042
          width: 128
          config:
            borderWidth: 0.5
          items:
              - !text
                fontSize: 43
                text: ' '
                backgroundColor: white
        - !columns
          absoluteY: 60
          absoluteX: 1045
          width: 124
          nbColumns: 1
          items:
            - !scalebar
                type: line
                units: m
                color: black
                align: center
                vertAlign: top
                fontSize: 8
                maxSize: 128
            - !text
              condition: langde
              fontSize: 7
              align: center
              text: |
                Massstab 1: ${format %,d scale}
                Gedruckt am ${now dd.MM.yyyy HH:mm}
                ${shortLink}
            - !text
              condition: langen
              fontSize: 7
              align: center
              text: |
                Scale 1: ${format %,d scale}
                Printed on ${now dd.MM.yyyy HH:mm}
                ${shortLink}

#---------------------------------------
# North arrow
#---------------------------------------
        - !columns
          absoluteX: 995
          absoluteY: 60
          width: 30
          items:
            - !image
              rotation: '${rotation}'
              align: right
              maxWidth: 30
              maxHeight: 30
              url: "${northArrow}"

    lastPage:
      landscape: true
      items:

##---------------------------------------
## Legend title
##---------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 575
          width: 798
          condition: "enableLegends"
          items:
            - !text
              fontSize: 12
              align: center
              text: |
                ${legendTitle}

##--------------------------------------
## Legend
##--------------------------------------
        - !columns
          absoluteX: 22
          absoluteY: 555
          width: 798
          condition: "enableLegends"
          items:
            - !legends
              horizontalAlignment: left
              maxHeight: 420
              maxWidth: 0
              iconMaxWidth: 200
              iconMaxHeight: 420
              defaultScale: 0.75
              classIndentation: 3
              layerSpace: 5
              classSpace: 5
              layerFontSize: 6
              columnMargin: 5
              backgroundColor: white
              inline: false
